import type { WordSearchThemeSeed } from '../../engine/seedCorpus';

const en: WordSearchThemeSeed[] = [
  {
    themeId: 'animals',
    words: [
      'Dog', 'Cat', 'Horse', 'Cow', 'Sheep', 'Goat', 'Pig', 'Donkey', 'Camel', 'Llama',
      'Tiger', 'Lion', 'Panther', 'Jaguar', 'Leopard', 'Cheetah', 'Wolf', 'Fox', 'Bear', 'Panda',
      'Raccoon', 'Beaver', 'Otter', 'Deer', 'Roe', 'Bison', 'Buffalo', 'Zebra', 'Wildebeest', 'Elephant',
      'Rhino', 'Hippo', 'Monkey', 'Gorilla', 'Chimpanzee', 'Lemur', 'Snake', 'Lizard', 'Frog', 'Toad',
      'Turtle', 'Eagle', 'Hawk', 'Owl', 'Dove', 'Crow', 'Magpie', 'Swan', 'Gull', 'Heron',
      'Marten', 'Badger', 'Hedgehog', 'Mole', 'Bat', 'Walrus', 'Seal', 'Dolphin', 'Shark', 'Whale',
      'Cod', 'Trout', 'Salmon', 'Octopus', 'Crab', 'Shrimp', 'Ant', 'Wasp', 'Bee', 'Dragonfly',
      'Vulture', 'Turkey', 'Pheasant', 'Partridge', 'Chicken', 'Rooster', 'Duck', 'Goose', 'Flamingo', 'Pelican',
      'Chameleon', 'Iguana', 'Python', 'Boa', 'Adder', 'Scorpion', 'Spider', 'Tarantula', 'Termite', 'Grasshopper',
      'Beetle', 'Butterfly', 'Moth', 'Seahorse', 'Ray', 'Tuna', 'Mackerel', 'Sardine', 'Oyster', 'Mussel',
      'Eel', 'Squid', 'Lobster', 'Jellyfish', 'Orca', 'Hen', 'Bull', 'Clam', 'Herring', 'Starfish',
      'Parrot', 'Penguin', 'Ostrich', 'Sparrow', 'Robin', 'Pigeon', 'Peacock', 'Toucan', 'Stork', 'Crane',
      'Crocodile', 'Alligator', 'Gecko', 'Tortoise', 'Cobra', 'Mamba', 'Viper', 'Firefly', 'Ladybug', 'Mosquito',
      'Caterpillar', 'Flea', 'Hornet', 'Bumblebee', 'Cockroach',
    ],
  },
  {
    themeId: 'food',
    words: [
      'Apple', 'Pear', 'Banana', 'Mango', 'Kiwi', 'Grape', 'Cherry', 'Plum', 'Peach', 'Apricot',
      'Strawberry', 'Raspberry', 'Blackberry', 'Blueberry', 'Lemon', 'Lime', 'Orange', 'Mandarin', 'Grapefruit', 'Avocado',
      'Coconut', 'Watermelon', 'Pineapple', 'Papaya', 'Fig', 'Cranberry', 'Melon', 'Dates', 'Guava', 'Carrot',
      'Potato', 'Onion', 'Garlic', 'Pea', 'Bean', 'Corn', 'Broccoli', 'Spinach', 'Lettuce', 'Cabbage',
      'Tomato', 'Cucumber', 'Pepper', 'Mushroom', 'Celery', 'Leek', 'Pumpkin', 'Zucchini', 'Cauliflower', 'Asparagus',
      'Beetroot', 'Kale', 'Radish', 'Lentil', 'Eggplant', 'Squash', 'Pie', 'Soup', 'Stew', 'Toast',
      'Salad', 'Pasta', 'Pizza', 'Curry', 'Steak', 'Burger', 'Sandwich', 'Pancake', 'Waffle', 'Muffin',
      'Cookie', 'Cake', 'Donut', 'Brownie', 'Noodle', 'Bread', 'Omelette', 'Sausage', 'Pudding', 'Tart',
      'Granola', 'Roll', 'Ham', 'Egg', 'Rice', 'Beef', 'Pork', 'Lamb', 'Honey', 'Jam',
      'Cheese', 'Butter', 'Milk', 'Yogurt', 'Cream', 'Tea', 'Coffee', 'Juice', 'Chocolate', 'Ginger',
      'Pomegranate', 'Tangerine', 'Nectarine', 'Artichoke', 'Parsnip', 'Basil', 'Mint', 'Cinnamon', 'Vanilla', 'Sushi',
      'Taco', 'Risotto', 'Lasagne', 'Croissant', 'Kebab', 'Paella', 'Smoothie', 'Sugar', 'Flour', 'Syrup',
      'Water', 'Lemonade', 'Milkshake', 'Cocoa', 'Cider', 'Burrito', 'Ramen', 'Bagel', 'Crepe', 'Falafel',
      'Nachos', 'Dumpling', 'Quiche', 'Salt', 'Oil', 'Oat', 'Tofu', 'Drumstick', 'Turnip', 'Fennel',
    ],
  },
  {
    themeId: 'nature',
    words: [
      'Rose', 'Tulip', 'Sunflower', 'Daisy', 'Lavender', 'Lily', 'Orchid', 'Poppy', 'Iris', 'Violet',
      'Carnation', 'Dahlia', 'Daffodil', 'Jasmine', 'Hibiscus', 'Magnolia', 'Bluebell', 'Snowdrop', 'Primrose', 'Buttercup',
      'Heather', 'Clover', 'Lilac', 'Peony', 'Wisteria', 'Foxglove', 'Oak', 'Birch', 'Maple', 'Willow',
      'Pine', 'Palm', 'Spruce', 'Beech', 'Cedar', 'Elm', 'Ash', 'Poplar', 'Cypress', 'Larch',
      'Sequoia', 'Sycamore', 'Fern', 'Ivy', 'Cactus', 'Aloe', 'Dandelion', 'Nettle', 'Thistle', 'Moss',
      'Bamboo', 'Vine', 'Rain', 'Snow', 'Storm', 'Thunder', 'Lightning', 'Fog', 'Cloud', 'Wind',
      'Frost', 'Hail', 'Ice', 'Rainbow', 'Blizzard', 'Tornado', 'Hurricane', 'Drizzle', 'Mist', 'Breeze',
      'Sleet', 'Aurora', 'Sunshine', 'Snowflake', 'Forest', 'River', 'Lake', 'Mountain', 'Valley', 'Beach',
      'Desert', 'Ocean', 'Cliff', 'Cave', 'Waterfall', 'Island', 'Meadow', 'Glacier', 'Volcano', 'Jungle',
      'Canyon', 'Swamp', 'Prairie', 'Dune', 'Pond', 'Stream', 'Marsh', 'Lagoon', 'Reef', 'Plateau',
      'Savanna', 'Tundra', 'Moor', 'Fjord', 'Bay', 'Gorge', 'Ridge', 'Peak', 'Creek', 'Pebble',
      'Spring', 'Summer', 'Autumn', 'Winter', 'Sunrise', 'Sunset', 'Eclipse', 'Tide', 'Pollen', 'Soil',
    ],
  },
  {
    themeId: 'sports',
    words: [
      'Football', 'Handball', 'Basketball', 'Volleyball', 'Hockey', 'Tennis', 'Badminton', 'Squash', 'Rugby', 'Baseball',
      'Softball', 'Athletics', 'Sprint', 'Marathon', 'Triathlon', 'Swimming', 'Waterpolo', 'Diving', 'Fencing', 'Judo',
      'Karate', 'Taekwondo', 'Boxing', 'Wrestling', 'Gymnastics', 'Golf', 'Cricket', 'Skiing', 'Snowboarding', 'Skating',
      'Curling', 'Rowing', 'Sailing', 'Surfing', 'Kitesurfing', 'Windsurfing', 'Canoeing', 'Kayaking', 'Archery', 'Darts',
      'Billiards', 'Snooker', 'Esports', 'Weightlifting', 'Riding', 'Hiking', 'Climbing', 'Cycling', 'Jogging', 'Luge',
      'Racket', 'Helmet', 'Gloves', 'Bat', 'Club', 'Net', 'Goal', 'Hoop', 'Puck', 'Arrow',
      'Bow', 'Mat', 'Ring', 'Court', 'Whistle', 'Trophy', 'Medal', 'Scoreboard', 'Stopwatch', 'Paddle',
      'Rope', 'Saddle', 'Skis', 'Jersey', 'Cleats',
    ],
  },
  {
    themeId: 'clothing',
    words: [
      'Tshirt', 'Sweater', 'Cardigan', 'Jacket', 'Blouse', 'Shirt', 'Polo', 'Tanktop', 'Trousers', 'Jeans',
      'Leggings', 'Skirt', 'Dress', 'Shorts', 'Pajamas', 'Socks', 'Tights', 'Beanie', 'Scarf', 'Cap',
      'Hat', 'Sneakers', 'Boots', 'Sandals', 'Heels', 'Slippers', 'Belt', 'Bikini', 'Swimsuit', 'Overalls',
      'Suit', 'Blazer', 'Hoodie', 'Poncho', 'Kimono', 'Tracksuit', 'Waistcoat', 'Stockings', 'Raincoat', 'Wintercoat',
      'Parka', 'Pullover', 'Gloves', 'Mittens', 'Vest', 'Dungarees', 'Jumpsuit', 'Robe', 'Tunic', 'Kilt',
      'Necklace', 'Bracelet', 'Earring', 'Watch', 'Sunglasses', 'Handbag', 'Wallet', 'Umbrella', 'Headband', 'Tie',
      'Bowtie', 'Ribbon', 'Cotton', 'Silk', 'Wool', 'Linen', 'Denim', 'Velvet', 'Leather', 'Polyester',
      'Nylon', 'Fleece', 'Cashmere', 'Satin', 'Suede',
    ],
  },
  {
    themeId: 'transport',
    words: [
      'Car', 'Bus', 'Bicycle', 'Motorcycle', 'Scooter', 'Tractor', 'Ambulance', 'Taxi', 'Limousine', 'Camper',
      'Caravan', 'Train', 'Metro', 'Tram', 'Monorail', 'Boat', 'Sailboat', 'Motorboat', 'Submarine', 'Airplane',
      'Helicopter', 'Zeppelin', 'Drone', 'Spaceship', 'Quad', 'Snowmobile', 'Bulldozer', 'Excavator', 'Truck', 'Minivan',
      'Convertible', 'Coupe', 'Sedan', 'Roadster', 'Forklift', 'Segway', 'Hovercraft', 'Jetski', 'Speedboat', 'Gokart',
      'Rickshaw', 'Moped', 'Glider', 'Ferry', 'Barge', 'Canoe', 'Kayak', 'Raft', 'Wagon', 'Sled',
    ],
  },
  {
    themeId: 'home',
    words: [
      'Knife', 'Fork', 'Spoon', 'Spatula', 'Whisk', 'Tongs', 'Peeler', 'Grater', 'Colander', 'Scale',
      'Pan', 'Wok', 'Saucepan', 'Blender', 'Toaster', 'Kettle', 'Microwave', 'Oven', 'Stove', 'Grill',
      'Ladle', 'Bowl', 'Plate', 'Mug', 'Mixer', 'Tray', 'Rack', 'Scoop', 'Casserole', 'Stockpot',
      'Cup', 'Glass', 'Jug', 'Pot', 'Jar', 'Bottle', 'Teapot', 'Flask', 'Cooker', 'Freezer',
      'Kitchen', 'Bedroom', 'Bathroom', 'Hallway', 'Attic', 'Basement', 'Garage', 'Garden', 'Balcony', 'Study',
      'Porch', 'Patio', 'Pantry', 'Nursery', 'Lounge', 'Corridor', 'Cellar', 'Laundry', 'Chair', 'Sofa',
      'Table', 'Desk', 'Bed', 'Shelf', 'Wardrobe', 'Drawer', 'Lamp', 'Mirror', 'Rug', 'Curtain',
      'Pillow', 'Blanket', 'Cabinet', 'Bookcase', 'Armchair', 'Stool', 'Couch', 'Dresser', 'Fireplace', 'Sideboard',
      'Nightstand', 'Headboard', 'Footrest', 'Hammock', 'Cot', 'Recliner', 'Vase', 'Frame', 'Cushion', 'Doormat',
      'Fridge', 'Washer', 'Dryer', 'Vacuum', 'Dishwasher', 'Television', 'Heater', 'Fan', 'Radio', 'Iron',
      'Printer', 'Laptop', 'Phone', 'Broom', 'Mop', 'Bucket', 'Towel', 'Soap', 'Candle', 'Clock',
      'Door', 'Window', 'Key', 'Shower', 'Bathtub', 'Basket', 'Hanger', 'Sponge', 'Bench', 'Ottoman',
      'Shovel', 'Spade', 'Rake', 'Hoe', 'Trowel', 'Wheelbarrow', 'Lawnmower', 'Sprinkler', 'Hose', 'Greenhouse',
      'Shed', 'Fence', 'Gate', 'Hedge', 'Bush', 'Lawn', 'Flowerpot', 'Planter', 'Compost', 'Mulch',
      'Pruner', 'Ladder', 'Trellis', 'Birdbath', 'Pathway',
    ],
  },
  {
    themeId: 'professions',
    words: [
      'Doctor', 'Nurse', 'Carpenter', 'Plumber', 'Baker', 'Butcher', 'Chef', 'Pilot', 'Driver', 'Firefighter',
      'Lawyer', 'Judge', 'Painter', 'Architect', 'Engineer', 'Designer', 'Journalist', 'Writer', 'Actor', 'Singer',
      'Musician', 'Gardener', 'Farmer', 'Mechanic', 'Trainer', 'Coach', 'Teacher', 'Professor', 'Barista', 'Waiter',
      'Pharmacist', 'Caregiver', 'Therapist', 'Photographer', 'Artist', 'Plasterer', 'Optician', 'Surgeon', 'Dentist', 'Analyst',
      'Accountant', 'Inspector', 'Technician', 'Planner', 'Editor', 'Producer', 'Director', 'Animator', 'Stylist', 'Barber',
    ],
  },
  {
    themeId: 'family',
    words: [
      'Father', 'Mother', 'Son', 'Daughter', 'Brother', 'Sister', 'Grandpa', 'Grandma', 'Uncle', 'Aunt',
      'Nephew', 'Niece', 'Godfather', 'Godmother', 'Groom', 'Bride', 'Husband', 'Wife', 'Partner', 'Fiance',
      'Child', 'Baby', 'Toddler', 'Teenager', 'Adult', 'Senior', 'Grandson', 'Granddaughter', 'Stepfather', 'Stepmother',
      'Stepbrother', 'Stepsister', 'Household', 'Family', 'Ancestor', 'Offspring', 'Relative', 'Guardian', 'Sibling', 'Parent',
      'Cousin', 'Twin', 'Infant', 'Newborn', 'Orphan', 'Widow', 'Elder', 'Kin', 'Clan', 'Tribe',
    ],
  },
  {
    themeId: 'traits',
    words: [
      'Kind', 'Smart', 'Strong', 'Brave', 'Honest', 'Creative', 'Patient', 'Helpful', 'Friendly', 'Caring',
      'Calm', 'Cool', 'Funny', 'Serious', 'Reliable', 'Ambitious', 'Social', 'Precise', 'Flexible', 'Modest',
      'Gentle', 'Strict', 'Sensitive', 'Fiery', 'Orderly', 'Cheerful', 'Grounded', 'Logical', 'Empathetic', 'Practical',
      'Handy', 'Resolute', 'Upright', 'Careful', 'Courageous', 'Energetic', 'Loyal', 'Curious', 'Dedicated', 'Attentive',
      'Optimistic', 'Determined', 'Charismatic', 'Independent', 'Resourceful', 'Thoughtful', 'Diligent', 'Sincere', 'Witty', 'Bold',
    ],
  },
  {
    themeId: 'space',
    words: [
      'Star', 'Planet', 'Moon', 'Sun', 'Comet', 'Meteor', 'Nebula', 'Cluster', 'Supernova', 'Galaxy',
      'Quasar', 'Pulsar', 'Vacuum', 'Rocket', 'Shuttle', 'Satellite', 'Telescope', 'Astronaut', 'Orbit', 'Gravity',
      'Plasma', 'Matter', 'Crater', 'Core', 'Mantle', 'Space', 'Universe', 'Cosmos', 'Darkness', 'Horizon',
      'Atmosphere', 'Radiation', 'Exoplanet', 'Trajectory', 'Lightyear', 'Constellation', 'Observatory', 'Cosmonaut', 'Spacestation', 'Blackhole',
      'Milkyway', 'Antimatter', 'Solarwind', 'Solarflare', 'Asteroid', 'Wormhole', 'Nebulae', 'Eclipse', 'Solstice', 'Zenith',
    ],
  },
  {
    themeId: 'colors',
    words: [
      'Red', 'Tan', 'Buff', 'Gold', 'Blue', 'Pink', 'Gray', 'Teal', 'Cyan', 'Navy',
      'Aqua', 'Lime', 'Rose', 'Jade', 'Rust', 'Ecru', 'Coral', 'Peach', 'Cream', 'Ivory',
      'Beige', 'Amber', 'Olive', 'Lilac', 'Mauve', 'Green', 'Brown', 'Black', 'White', 'Azure',
      'Ochre', 'Taupe', 'Maroon', 'Violet', 'Indigo', 'Salmon', 'Bronze', 'Copper', 'Cobalt', 'Silver',
      'Purple', 'Orange', 'Yellow', 'Crimson', 'Scarlet', 'Fuchsia', 'Magenta', 'Lavender', 'Turquoise', 'Charcoal',
    ],
  },
  {
    themeId: 'bodyparts',
    words: [
      'Eye', 'Ear', 'Arm', 'Leg', 'Hip', 'Jaw', 'Toe', 'Rib', 'Lip', 'Gum',
      'Shin', 'Knee', 'Nose', 'Back', 'Neck', 'Heel', 'Hand', 'Foot', 'Nail', 'Hair',
      'Skin', 'Bone', 'Chin', 'Brow', 'Palm', 'Calf', 'Wrist', 'Ankle', 'Thumb', 'Elbow',
      'Cheek', 'Chest', 'Spine', 'Thigh', 'Scalp', 'Heart', 'Belly', 'Brain', 'Tooth', 'Finger',
      'Temple', 'Tongue', 'Armpit', 'Kidney', 'Muscle', 'Eyelid', 'Shoulder', 'Stomach', 'Forehead', 'Kneecap',
    ],
  },
  {
    themeId: 'school',
    words: [
      'Pen', 'Ink', 'Book', 'Desk', 'Glue', 'Tape', 'Exam', 'Test', 'Quiz', 'Board',
      'Ruler', 'Chalk', 'Paint', 'Globe', 'Atlas', 'Class', 'Grade', 'Score', 'Lunch', 'Study',
      'Pencil', 'Folder', 'Binder', 'Staple', 'Crayon', 'Eraser', 'Marker', 'Locker', 'Lesson', 'Recess',
      'Journal', 'Compass', 'Palette', 'Cabinet', 'Scanner', 'Notebook', 'Backpack', 'Scissors', 'Textbook', 'Workbook',
      'Homework', 'Calendar', 'Schedule', 'Classroom', 'Timetable', 'Library', 'Teacher', 'Student', 'Science', 'History',
    ],
  },
  {
    themeId: 'music',
    words: [
      'Drum', 'Guitar', 'Piano', 'Violin', 'Trumpet', 'Flute', 'Harp', 'Cello', 'Tuba', 'Trombone',
      'Clarinet', 'Accordion', 'Ukulele', 'Banjo', 'Saxophone', 'Keyboard', 'Recorder', 'Xylophone', 'Bell', 'Cymbal',
      'Gong', 'Bass', 'Tambourine', 'Harmonica', 'Viola', 'Triangle', 'Bagpipes', 'Synthesizer', 'Microphone', 'Harpsichord',
      'Beat', 'Tune', 'Note', 'Melody', 'Rhythm', 'Chorus', 'Tempo', 'Pitch', 'Chord', 'Harmony',
      'Concert', 'Album', 'Song', 'Singer', 'Band', 'Solo', 'Duet', 'Orchestra', 'Acoustic', 'Lyrics',
      'Verse', 'Bridge', 'Riff', 'Groove', 'Remix', 'Track', 'Encore', 'Voice', 'Choir', 'Rehearsal',
      'Festival', 'Stage', 'Studio', 'Composer', 'Conductor', 'Vocalist', 'Playlist', 'Recording', 'Volume', 'Tone',
      'Jazz', 'Blues', 'Rock', 'Pop', 'Classical', 'Folk', 'Reggae', 'Gospel', 'Opera', 'Rap',
      'Soul', 'Country', 'Funk', 'Disco', 'Punk', 'Metal', 'Techno', 'Indie', 'Ballad', 'Treble',
      'Dance', 'Swing', 'Waltz', 'Grunge', 'Electronic', 'Latin', 'Bluegrass', 'Celtic', 'Speaker', 'Headphones',
      'Vinyl', 'Record', 'Cassette', 'Turntable', 'Stereo', 'Amplifier', 'Jukebox', 'Boombox', 'Earphones', 'Karaoke',
      'Podcast', 'Mixer',
    ],
  },
];

export default en;
