import type { WordSearchThemeSeed } from '../../engine/seedCorpus';

const en: WordSearchThemeSeed[] = [
  {
    themeId: 'animals',
    words: [
      'Dog', 'Cat', 'Horse', 'Cow', 'Sheep', 'Goat', 'Pig', 'Donkey', 'Camel', 'Llama',
      'Tiger', 'Lion', 'Panther', 'Jaguar', 'Leopard', 'Cheetah', 'Wolf', 'Fox', 'Bear', 'Panda',
      'Raccoon', 'Beaver', 'Otter', 'Deer', 'Roe', 'Bison', 'Buffalo', 'Zebra', 'Wildebeest', 'Elephant',
      'Rhino', 'Hippo', 'Monkey', 'Gorilla', 'Chimpanzee', 'Lemur', 'Snake', 'Lizard', 'Frog', 'Toad',
      'Turtle', 'Eagle', 'Hawk', 'Owl', 'Dove', 'Crow', 'Magpie', 'Swan', 'Gull', 'Heron',
      'Marten', 'Badger', 'Hedgehog', 'Mole', 'Bat', 'Walrus', 'Seal', 'Dolphin', 'Shark', 'Whale',
      'Cod', 'Trout', 'Salmon', 'Octopus', 'Crab', 'Shrimp', 'Ant', 'Wasp', 'Bee', 'Dragonfly',
      'Vulture', 'Turkey', 'Pheasant', 'Partridge', 'Chicken', 'Rooster', 'Duck', 'Goose', 'Flamingo', 'Pelican',
      'Chameleon', 'Iguana', 'Python', 'Boa', 'Adder', 'Scorpion', 'Spider', 'Tarantula', 'Termite', 'Grasshopper',
      'Beetle', 'Butterfly', 'Moth', 'Seahorse', 'Ray', 'Tuna', 'Mackerel', 'Sardine', 'Oyster', 'Mussel',
      'Eel', 'Squid', 'Lobster', 'Jellyfish', 'Orca', 'Hen', 'Bull', 'Clam', 'Herring', 'Starfish',
      'Parrot', 'Penguin', 'Ostrich', 'Sparrow', 'Robin', 'Pigeon', 'Peacock', 'Toucan', 'Stork', 'Crane',
      'Crocodile', 'Alligator', 'Gecko', 'Tortoise', 'Cobra', 'Mamba', 'Viper', 'Firefly', 'Ladybug', 'Mosquito',
      'Caterpillar', 'Flea', 'Hornet', 'Bumblebee', 'Cockroach',
    ],
  },
  {
    themeId: 'food',
    words: [
      'Apple', 'Pear', 'Banana', 'Mango', 'Kiwi', 'Grape', 'Cherry', 'Plum', 'Peach', 'Apricot',
      'Strawberry', 'Raspberry', 'Blackberry', 'Blueberry', 'Lemon', 'Lime', 'Orange', 'Mandarin', 'Grapefruit', 'Avocado',
      'Coconut', 'Watermelon', 'Pineapple', 'Papaya', 'Fig', 'Cranberry', 'Melon', 'Dates', 'Guava', 'Carrot',
      'Potato', 'Onion', 'Garlic', 'Pea', 'Bean', 'Corn', 'Broccoli', 'Spinach', 'Lettuce', 'Cabbage',
      'Tomato', 'Cucumber', 'Pepper', 'Mushroom', 'Celery', 'Leek', 'Pumpkin', 'Zucchini', 'Cauliflower', 'Asparagus',
      'Beetroot', 'Kale', 'Radish', 'Lentil', 'Eggplant', 'Squash', 'Pie', 'Soup', 'Stew', 'Toast',
      'Salad', 'Pasta', 'Pizza', 'Curry', 'Steak', 'Burger', 'Sandwich', 'Pancake', 'Waffle', 'Muffin',
      'Cookie', 'Cake', 'Donut', 'Brownie', 'Noodle', 'Bread', 'Omelette', 'Sausage', 'Pudding', 'Tart',
      'Granola', 'Roll', 'Ham', 'Egg', 'Rice', 'Beef', 'Pork', 'Lamb', 'Honey', 'Jam',
      'Cheese', 'Butter', 'Milk', 'Yogurt', 'Cream', 'Tea', 'Coffee', 'Juice', 'Chocolate', 'Ginger',
      'Pomegranate', 'Tangerine', 'Nectarine', 'Artichoke', 'Parsnip', 'Basil', 'Mint', 'Cinnamon', 'Vanilla', 'Sushi',
      'Taco', 'Risotto', 'Lasagne', 'Croissant', 'Kebab', 'Paella', 'Smoothie', 'Sugar', 'Flour', 'Syrup',
      'Water', 'Lemonade', 'Milkshake', 'Cocoa', 'Cider', 'Burrito', 'Ramen', 'Bagel', 'Crepe', 'Falafel',
      'Nachos', 'Dumpling', 'Quiche', 'Salt', 'Oil', 'Oat', 'Tofu', 'Drumstick', 'Turnip', 'Fennel',
    ],
  },
  {
    themeId: 'nature',
    words: [
      'Rose', 'Tulip', 'Sunflower', 'Daisy', 'Lavender', 'Lily', 'Orchid', 'Poppy', 'Iris', 'Violet',
      'Carnation', 'Dahlia', 'Daffodil', 'Jasmine', 'Hibiscus', 'Magnolia', 'Bluebell', 'Snowdrop', 'Primrose', 'Buttercup',
      'Heather', 'Clover', 'Lilac', 'Peony', 'Wisteria', 'Foxglove', 'Oak', 'Birch', 'Maple', 'Willow',
      'Pine', 'Palm', 'Spruce', 'Beech', 'Cedar', 'Elm', 'Ash', 'Poplar', 'Cypress', 'Larch',
      'Sequoia', 'Sycamore', 'Fern', 'Ivy', 'Cactus', 'Aloe', 'Dandelion', 'Nettle', 'Thistle', 'Moss',
      'Bamboo', 'Vine', 'Forest', 'River', 'Lake', 'Mountain', 'Valley', 'Beach', 'Desert', 'Ocean',
      'Cliff', 'Cave', 'Waterfall', 'Island', 'Meadow', 'Glacier', 'Volcano', 'Jungle', 'Canyon', 'Swamp',
      'Prairie', 'Dune', 'Pond', 'Stream', 'Marsh', 'Lagoon', 'Reef', 'Plateau', 'Savanna', 'Tundra',
      'Moor', 'Fjord', 'Bay', 'Gorge', 'Ridge', 'Peak', 'Creek', 'Pebble', 'Spring', 'Summer',
      'Autumn', 'Winter', 'Sunrise', 'Sunset', 'Eclipse', 'Tide', 'Pollen', 'Soil',
    ],
  },
  {
    themeId: 'weather',
    words: [
      'Rain', 'Snow', 'Storm', 'Thunder', 'Lightning', 'Fog', 'Cloud', 'Wind', 'Frost', 'Hail',
      'Ice', 'Rainbow', 'Blizzard', 'Tornado', 'Hurricane', 'Drizzle', 'Mist', 'Breeze', 'Sleet', 'Aurora',
      'Sunshine', 'Snowflake', 'Cyclone', 'Typhoon', 'Monsoon', 'Gale', 'Humidity', 'Climate', 'Forecast', 'Avalanche',
      'Overcast', 'Drought', 'Flood', 'Heatwave', 'Chilly', 'Freezing', 'Scorching', 'Muggy', 'Humid', 'Arid',
      'Temperate', 'Tropical', 'Arctic', 'Polar', 'Twilight', 'Dawn', 'Dusk', 'Downpour', 'Gust', 'Squall',
      'Thunderstorm', 'Windstorm', 'Snowstorm', 'Whirlwind', 'Rainfall', 'Snowfall', 'Windchill', 'Sunbeam', 'Raindrop', 'Puddle',
      'Umbrella', 'Snowman', 'Snowball', 'Icicle', 'Thermometer', 'Barometer', 'Weathervane', 'Cloudburst', 'Hailstorm', 'Temperature',
      'Balmy', 'Breezy', 'Windy', 'Rainy', 'Snowy', 'Cloudy', 'Sunny', 'Stormy', 'Foggy', 'Misty',
      'Frosty', 'Icy', 'Hazy', 'Damp', 'Mild', 'Torrid', 'Blustery', 'Wintry', 'Sultry', 'Sweltering',
    ],
  },
  {
    themeId: 'sports',
    words: [
      'Football', 'Handball', 'Basketball', 'Volleyball', 'Hockey', 'Tennis', 'Badminton', 'Squash', 'Rugby', 'Baseball',
      'Softball', 'Athletics', 'Sprint', 'Marathon', 'Triathlon', 'Swimming', 'Waterpolo', 'Diving', 'Fencing', 'Judo',
      'Karate', 'Taekwondo', 'Boxing', 'Wrestling', 'Gymnastics', 'Golf', 'Cricket', 'Skiing', 'Snowboarding', 'Skating',
      'Curling', 'Rowing', 'Sailing', 'Surfing', 'Kitesurfing', 'Windsurfing', 'Canoeing', 'Kayaking', 'Archery', 'Darts',
      'Billiards', 'Snooker', 'Esports', 'Weightlifting', 'Riding', 'Hiking', 'Climbing', 'Cycling', 'Jogging', 'Luge',
      'Racket', 'Helmet', 'Gloves', 'Bat', 'Club', 'Net', 'Goal', 'Hoop', 'Puck', 'Arrow',
      'Bow', 'Mat', 'Ring', 'Court', 'Whistle', 'Trophy', 'Medal', 'Scoreboard', 'Stopwatch', 'Paddle',
      'Rope', 'Saddle', 'Skis', 'Jersey', 'Cleats',
      'Lacrosse', 'Bowling', 'Polo', 'Pentathlon', 'Decathlon', 'Biathlon', 'Motocross', 'Skateboarding', 'Parkour', 'Yoga',
      'Aerobics', 'Calisthenics', 'Powerlifting', 'Bodybuilding', 'Freerunning', 'Skydiving', 'Rafting', 'Orienteering', 'Trampolining', 'Rollerblading',
      'Netball', 'Cheerleading', 'Paintball', 'Dodgeball', 'Speedskating', 'Figureskating', 'Fieldhockey', 'Steeplechase', 'Hurdles', 'Relay',
      'Discus', 'Javelin', 'Umpire', 'Teammate', 'Spectator', 'Champion', 'Tournament', 'Halftime', 'Overtime', 'Foul',
      'Penalty', 'Wetsuit', 'Snorkel', 'Goggles', 'Dumbbell', 'Treadmill',
    ],
  },
  {
    themeId: 'clothing',
    words: [
      'Tshirt', 'Sweater', 'Cardigan', 'Jacket', 'Blouse', 'Shirt', 'Polo', 'Tanktop', 'Trousers', 'Jeans',
      'Leggings', 'Skirt', 'Dress', 'Shorts', 'Pajamas', 'Socks', 'Tights', 'Beanie', 'Scarf', 'Cap',
      'Hat', 'Sneakers', 'Boots', 'Sandals', 'Heels', 'Slippers', 'Belt', 'Bikini', 'Swimsuit', 'Overalls',
      'Suit', 'Blazer', 'Hoodie', 'Poncho', 'Kimono', 'Tracksuit', 'Waistcoat', 'Stockings', 'Raincoat', 'Wintercoat',
      'Parka', 'Pullover', 'Gloves', 'Mittens', 'Vest', 'Dungarees', 'Jumpsuit', 'Robe', 'Tunic', 'Kilt',
      'Necklace', 'Bracelet', 'Earring', 'Watch', 'Sunglasses', 'Handbag', 'Wallet', 'Umbrella', 'Headband', 'Tie',
      'Bowtie', 'Ribbon', 'Cotton', 'Silk', 'Wool', 'Linen', 'Denim', 'Velvet', 'Leather', 'Polyester',
      'Nylon', 'Fleece', 'Cashmere', 'Satin', 'Suede',
      'Turtleneck', 'Camisole', 'Romper', 'Bodysuit', 'Balaclava', 'Beret', 'Fedora', 'Sombrero', 'Bonnet', 'Visor',
      'Earmuffs', 'Muffler', 'Apron', 'Smock', 'Cape', 'Cloak', 'Shawl', 'Wrap', 'Sarong', 'Overcoat',
      'Windbreaker', 'Snowsuit', 'Onesie', 'Corset', 'Brooch', 'Cufflinks', 'Buckle', 'Zipper', 'Button', 'Collar',
      'Cuff', 'Pocket', 'Hem', 'Seam', 'Lace', 'Sequin', 'Tassel', 'Fringe', 'Pleat', 'Ruffle',
      'Corduroy', 'Chiffon', 'Tweed', 'Flannel', 'Tulle',
    ],
  },
  {
    themeId: 'transport',
    words: [
      'Car', 'Bus', 'Bicycle', 'Motorcycle', 'Scooter', 'Tractor', 'Ambulance', 'Taxi', 'Limousine', 'Camper',
      'Caravan', 'Train', 'Metro', 'Tram', 'Monorail', 'Boat', 'Sailboat', 'Motorboat', 'Submarine', 'Airplane',
      'Helicopter', 'Zeppelin', 'Drone', 'Spaceship', 'Quad', 'Snowmobile', 'Bulldozer', 'Excavator', 'Truck', 'Minivan',
      'Convertible', 'Coupe', 'Sedan', 'Roadster', 'Forklift', 'Segway', 'Hovercraft', 'Jetski', 'Speedboat', 'Gokart',
      'Rickshaw', 'Moped', 'Glider', 'Ferry', 'Barge', 'Canoe', 'Kayak', 'Raft', 'Wagon', 'Sled',
      'Freighter', 'Tanker', 'Yacht', 'Catamaran', 'Schooner', 'Trawler', 'Cruiser', 'Rowboat', 'Steamship', 'Liner',
      'Locomotive', 'Carriage', 'Streetcar', 'Cablecar', 'Minibus', 'Coach', 'Trailer', 'Caboose', 'Biplane', 'Airliner',
      'Seaplane', 'Paraglider', 'Parachute', 'Balloon', 'Airship', 'Blimp', 'Rover', 'Buggy', 'Unicycle', 'Tricycle',
      'Wheelchair', 'Stroller', 'Sidecar', 'Chariot', 'Sleigh', 'Toboggan', 'Icebreaker', 'Dinghy', 'Houseboat', 'Snowplow',
    ],
  },
  {
    themeId: 'home',
    words: [
      'Knife', 'Fork', 'Spoon', 'Spatula', 'Whisk', 'Tongs', 'Peeler', 'Grater', 'Colander', 'Scale',
      'Pan', 'Wok', 'Saucepan', 'Blender', 'Toaster', 'Kettle', 'Microwave', 'Oven', 'Stove', 'Grill',
      'Ladle', 'Bowl', 'Plate', 'Mug', 'Mixer', 'Tray', 'Rack', 'Scoop', 'Casserole', 'Stockpot',
      'Cup', 'Glass', 'Jug', 'Pot', 'Jar', 'Bottle', 'Teapot', 'Flask', 'Cooker', 'Freezer',
      'Kitchen', 'Bedroom', 'Bathroom', 'Hallway', 'Attic', 'Basement', 'Garage', 'Garden', 'Balcony', 'Study',
      'Porch', 'Patio', 'Pantry', 'Nursery', 'Lounge', 'Corridor', 'Cellar', 'Laundry', 'Chair', 'Sofa',
      'Table', 'Desk', 'Bed', 'Shelf', 'Wardrobe', 'Drawer', 'Lamp', 'Mirror', 'Rug', 'Curtain',
      'Pillow', 'Blanket', 'Cabinet', 'Bookcase', 'Armchair', 'Stool', 'Couch', 'Dresser', 'Fireplace', 'Sideboard',
      'Nightstand', 'Headboard', 'Footrest', 'Hammock', 'Cot', 'Recliner', 'Vase', 'Frame', 'Cushion', 'Doormat',
      'Fridge', 'Washer', 'Dryer', 'Vacuum', 'Dishwasher', 'Television', 'Heater', 'Fan', 'Radio', 'Iron',
      'Printer', 'Laptop', 'Phone', 'Broom', 'Mop', 'Bucket', 'Towel', 'Soap', 'Candle', 'Clock',
      'Door', 'Window', 'Key', 'Shower', 'Bathtub', 'Basket', 'Hanger', 'Sponge', 'Bench', 'Ottoman',
      'Shovel', 'Spade', 'Rake', 'Hoe', 'Trowel', 'Wheelbarrow', 'Lawnmower', 'Sprinkler', 'Hose', 'Greenhouse',
      'Shed', 'Fence', 'Gate', 'Hedge', 'Bush', 'Lawn', 'Flowerpot', 'Planter', 'Compost', 'Mulch',
      'Pruner', 'Ladder', 'Trellis', 'Birdbath', 'Pathway',
    ],
  },
  {
    themeId: 'professions',
    words: [
      'Doctor', 'Nurse', 'Carpenter', 'Plumber', 'Baker', 'Butcher', 'Chef', 'Pilot', 'Driver', 'Firefighter',
      'Lawyer', 'Judge', 'Painter', 'Architect', 'Engineer', 'Designer', 'Journalist', 'Writer', 'Actor', 'Singer',
      'Musician', 'Gardener', 'Farmer', 'Mechanic', 'Trainer', 'Coach', 'Teacher', 'Professor', 'Barista', 'Waiter',
      'Pharmacist', 'Caregiver', 'Therapist', 'Photographer', 'Artist', 'Plasterer', 'Optician', 'Surgeon', 'Dentist', 'Analyst',
      'Accountant', 'Inspector', 'Technician', 'Planner', 'Editor', 'Producer', 'Director', 'Animator', 'Stylist', 'Barber',
      'Electrician', 'Locksmith', 'Blacksmith', 'Roofer', 'Bricklayer', 'Welder', 'Tailor', 'Cobbler', 'Jeweler', 'Florist',
      'Butler', 'Janitor', 'Receptionist', 'Cashier', 'Banker', 'Mathematician', 'Physicist', 'Chemist', 'Biologist', 'Zoologist',
      'Botanist', 'Geologist', 'Astronomer', 'Historian', 'Translator', 'Illustrator', 'Referee', 'Lifeguard', 'Paramedic', 'Veterinarian',
      'Midwife', 'Psychologist', 'Explorer', 'Captain', 'Sailor', 'Officer', 'Miner', 'Shepherd', 'Beekeeper', 'Zookeeper',
      'Meteorologist', 'Programmer', 'Magician',
    ],
  },
  {
    themeId: 'emotions',
    words: [
      'Happy', 'Sad', 'Angry', 'Calm', 'Shy', 'Proud', 'Eager', 'Tense', 'Timid', 'Silly',
      'Scared', 'Nervous', 'Jealous', 'Lonely', 'Cheerful', 'Grumpy', 'Gloomy', 'Joyful', 'Amused', 'Bored',
      'Excited', 'Curious', 'Worried', 'Content', 'Thrilled', 'Anxious', 'Hopeful', 'Restless', 'Playful', 'Giddy',
      'Confused', 'Grateful', 'Peaceful', 'Relieved', 'Cranky', 'Moody', 'Sulky', 'Uneasy', 'Serene', 'Cozy',
      'Confident', 'Surprised', 'Delighted', 'Terrified', 'Miserable', 'Irritated', 'Fearful', 'Startled', 'Puzzled', 'Amazed',
      'Frustrated', 'Disappointed', 'Enthusiastic', 'Affectionate', 'Overjoyed', 'Agitated', 'Satisfied', 'Hesitant', 'Determined', 'Motivated',
      'Embarrassed', 'Discouraged', 'Regretful', 'Guilty', 'Ashamed', 'Cautious', 'Suspicious', 'Trusting', 'Loving', 'Caring',
      'Sensitive', 'Insecure', 'Astonished', 'Homesick', 'Heartbroken', 'Thankful', 'Blissful', 'Devoted', 'Comfortable', 'Impatient',
      'Stressed', 'Exhausted', 'Sleepy', 'Energetic', 'Alert', 'Distracted', 'Focused', 'Warmhearted', 'Sympathetic', 'Envious',
    ],
  },
  {
    themeId: 'space',
    words: [
      'Star', 'Planet', 'Moon', 'Sun', 'Comet', 'Meteor', 'Nebula', 'Cluster', 'Supernova', 'Galaxy',
      'Quasar', 'Pulsar', 'Vacuum', 'Rocket', 'Shuttle', 'Satellite', 'Telescope', 'Astronaut', 'Orbit', 'Gravity',
      'Plasma', 'Matter', 'Crater', 'Core', 'Mantle', 'Space', 'Universe', 'Cosmos', 'Darkness', 'Horizon',
      'Atmosphere', 'Radiation', 'Exoplanet', 'Trajectory', 'Lightyear', 'Constellation', 'Observatory', 'Cosmonaut', 'Spacestation', 'Blackhole',
      'Milkyway', 'Antimatter', 'Solarwind', 'Solarflare', 'Asteroid', 'Wormhole', 'Spacewalk', 'Eclipse', 'Solstice', 'Zenith',
      'Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Meteorite',
      'Meteoroid', 'Spacecraft', 'Interstellar', 'Alien', 'Spacesuit', 'Module', 'Capsule', 'Booster', 'Launchpad', 'Countdown',
      'Liftoff', 'Splashdown', 'Docking', 'Airlock', 'Probe', 'Lander', 'Stardust', 'Starlight', 'Cosmic', 'Galactic',
      'Celestial', 'Interplanetary', 'Weightlessness', 'Freefall', 'Debris',
      'Spacetime', 'Multiverse', 'Lightspeed', 'Mission', 'Crew', 'Payload', 'Reentry', 'Spacerace', 'Planetarium', 'Stargazing',
      'Nightsky', 'Deepspace', 'Outerspace', 'Bigbang', 'Spacetravel', 'Astronomy', 'Spaceport',
    ],
  },
  {
    themeId: 'art',
    words: [
      'Red', 'Tan', 'Gold', 'Blue', 'Pink', 'Gray', 'Teal', 'Cyan', 'Navy', 'Aqua',
      'Lime', 'Rose', 'Jade', 'Rust', 'Coral', 'Peach', 'Cream', 'Ivory', 'Beige', 'Amber',
      'Olive', 'Lilac', 'Mauve', 'Green', 'Brown', 'Black', 'White', 'Azure', 'Ochre', 'Maroon',
      'Violet', 'Indigo', 'Salmon', 'Bronze', 'Copper', 'Cobalt', 'Silver', 'Purple', 'Orange', 'Yellow',
      'Crimson', 'Scarlet', 'Fuchsia', 'Magenta', 'Lavender', 'Turquoise', 'Charcoal', 'Paint', 'Brush', 'Canvas',
      'Easel', 'Palette', 'Crayon', 'Pastel', 'Marker', 'Sketch', 'Eraser', 'Stencil', 'Sponge', 'Roller',
      'Varnish', 'Clay', 'Glitter', 'Sculpture', 'Mosaic', 'Collage', 'Frame', 'Gallery', 'Museum', 'Studio',
      'Exhibition', 'Portrait', 'Landscape', 'Abstract', 'Realism', 'Doodle', 'Drawing', 'Painting', 'Etching', 'Engraving',
      'Calligraphy', 'Origami', 'Pottery', 'Ceramics', 'Illustration', 'Cartoon', 'Graffiti', 'Mural', 'Fresco', 'Watercolor',
      'Acrylic', 'Silhouette', 'Composition', 'Perspective', 'Symmetry', 'Texture', 'Pattern', 'Design', 'Craft', 'Carving',
      'Weaving', 'Embroidery', 'Artist', 'Painter', 'Sculptor', 'Illustrator', 'Potter',
    ],
  },
  {
    themeId: 'bodyparts',
    words: [
      'Eye', 'Ear', 'Arm', 'Leg', 'Hip', 'Jaw', 'Toe', 'Rib', 'Lip', 'Gum',
      'Shin', 'Knee', 'Nose', 'Back', 'Neck', 'Heel', 'Hand', 'Foot', 'Nail', 'Hair',
      'Skin', 'Bone', 'Chin', 'Brow', 'Palm', 'Calf', 'Wrist', 'Ankle', 'Thumb', 'Elbow',
      'Cheek', 'Chest', 'Spine', 'Thigh', 'Scalp', 'Heart', 'Belly', 'Brain', 'Tooth', 'Finger',
      'Temple', 'Tongue', 'Armpit', 'Kidney', 'Muscle', 'Eyelid', 'Shoulder', 'Stomach', 'Forehead', 'Kneecap',
      'Liver', 'Lung', 'Bladder', 'Intestine', 'Pancreas', 'Spleen', 'Ligament', 'Tendon', 'Cartilage', 'Vertebra',
      'Sternum', 'Pelvis', 'Skull', 'Retina', 'Cornea', 'Pupil', 'Eardrum', 'Nostril', 'Eyebrow', 'Eyelash',
      'Forearm', 'Bicep', 'Tricep', 'Hamstring', 'Sole', 'Instep', 'Knuckle', 'Fingernail', 'Earlobe', 'Windpipe',
      'Vein', 'Artery', 'Ribcage', 'Collarbone', 'Cheekbone', 'Torso', 'Waist', 'Bellybutton', 'Eyeball', 'Jawline',
      'Hairline', 'Fingertip', 'Toenail',
    ],
  },
  {
    themeId: 'school',
    words: [
      'Pen', 'Ink', 'Book', 'Desk', 'Glue', 'Tape', 'Exam', 'Test', 'Quiz', 'Board',
      'Ruler', 'Chalk', 'Paint', 'Globe', 'Atlas', 'Class', 'Grade', 'Score', 'Lunch', 'Study',
      'Pencil', 'Folder', 'Binder', 'Staple', 'Crayon', 'Eraser', 'Marker', 'Locker', 'Lesson', 'Recess',
      'Journal', 'Compass', 'Palette', 'Cabinet', 'Scanner', 'Notebook', 'Backpack', 'Scissors', 'Textbook', 'Workbook',
      'Homework', 'Calendar', 'Schedule', 'Classroom', 'Timetable', 'Library', 'Teacher', 'Student', 'Science', 'History',
      'Tutor', 'Office', 'Report', 'Biology', 'Physics', 'Grammar', 'Reading', 'Writing', 'Uniform', 'Diploma',
      'Project', 'Diagram', 'Spelling', 'Corridor', 'Envelope', 'Bookmark', 'Alphabet', 'Fraction', 'Equation', 'Vacation',
      'Assembly', 'Geography', 'Chemistry', 'Principal', 'Classmate', 'Librarian', 'Custodian', 'Counselor', 'Cafeteria', 'Gymnasium',
      'Bookshelf', 'Projector', 'Clipboard', 'Sharpener', 'Worksheet', 'Detention', 'Auditorium', 'Playground', 'Blackboard', 'Whiteboard',
      'Arithmetic', 'Literature', 'Microscope', 'Calculator', 'Protractor', 'Dictionary', 'Vocabulary', 'Mathematics', 'Highlighter', 'Certificate',
      'Encyclopedia',
    ],
  },
  {
    themeId: 'music',
    words: [
      'Drum', 'Guitar', 'Piano', 'Violin', 'Trumpet', 'Flute', 'Harp', 'Cello', 'Tuba', 'Trombone',
      'Clarinet', 'Accordion', 'Ukulele', 'Banjo', 'Saxophone', 'Keyboard', 'Recorder', 'Xylophone', 'Bell', 'Cymbal',
      'Gong', 'Bass', 'Tambourine', 'Harmonica', 'Viola', 'Triangle', 'Bagpipes', 'Synthesizer', 'Microphone', 'Harpsichord',
      'Beat', 'Tune', 'Note', 'Melody', 'Rhythm', 'Chorus', 'Tempo', 'Pitch', 'Chord', 'Harmony',
      'Concert', 'Album', 'Song', 'Singer', 'Band', 'Solo', 'Duet', 'Orchestra', 'Acoustic', 'Lyrics',
      'Verse', 'Bridge', 'Riff', 'Groove', 'Remix', 'Track', 'Encore', 'Voice', 'Choir', 'Rehearsal',
      'Festival', 'Stage', 'Studio', 'Composer', 'Conductor', 'Vocalist', 'Playlist', 'Recording', 'Volume', 'Tone',
      'Jazz', 'Blues', 'Rock', 'Pop', 'Classical', 'Folk', 'Reggae', 'Gospel', 'Opera', 'Rap',
      'Soul', 'Country', 'Funk', 'Disco', 'Punk', 'Metal', 'Techno', 'Indie', 'Ballad', 'Treble',
      'Dance', 'Swing', 'Waltz', 'Grunge', 'Electronic', 'Latin', 'Bluegrass', 'Celtic', 'Speaker', 'Headphones',
      'Vinyl', 'Record', 'Cassette', 'Turntable', 'Stereo', 'Amplifier', 'Jukebox', 'Boombox', 'Earphones', 'Karaoke',
      'Podcast', 'Mixer',
    ],
  },
  {
    themeId: 'technology',
    words: [
      'Computer', 'Laptop', 'Desktop', 'Keyboard', 'Mouse', 'Monitor', 'Screen', 'Touchscreen', 'Printer', 'Scanner',
      'Speaker', 'Headphones', 'Headset', 'Earbuds', 'Microphone', 'Camera', 'Webcam', 'Router', 'Modem', 'Server',
      'Processor', 'Chip', 'Microchip', 'Circuit', 'Battery', 'Charger', 'Cable', 'Adapter', 'Drive', 'Disk',
      'Memory', 'Storage', 'Motherboard', 'Fan', 'Cooler', 'Joystick', 'Controller', 'Console', 'Tablet', 'Smartphone',
      'Smartwatch', 'Projector', 'Socket', 'Plug', 'Switch', 'Sensor', 'Antenna', 'Satellite', 'Transistor', 'Cartridge',
      'Keypad', 'Trackpad', 'Stylus', 'Remote', 'Amplifier', 'Transmitter', 'Receiver', 'Terminal', 'Dashboard', 'Firmware',
      'Gadget', 'Device', 'Drone', 'Hologram', 'Handset', 'Software', 'Hardware', 'Program', 'Application', 'Website',
      'Webpage', 'Browser', 'Internet', 'Network', 'Database', 'Algorithm', 'Code', 'Coding', 'Programming', 'Script',
      'Function', 'Variable', 'Debug', 'Compiler', 'Interface', 'Icon', 'Cursor', 'Folder', 'Document', 'Spreadsheet',
      'Presentation', 'Template', 'Format', 'Backup', 'Update', 'Upgrade', 'Install', 'Download', 'Upload', 'Stream',
      'Streaming', 'Buffer', 'Cache', 'Cloud', 'Client', 'Password', 'Username', 'Login', 'Account', 'Profile',
      'Firewall', 'Encryption', 'Virus', 'Malware', 'Antivirus', 'Security', 'Privacy', 'Cookie', 'Bookmark', 'Window',
      'Menu', 'Toolbar', 'Widget', 'Notification', 'Message', 'Email', 'Chat', 'Video', 'Audio', 'Podcast',
      'Blog', 'Forum', 'Comment', 'Share', 'Subscribe', 'Feed', 'Search', 'Filter', 'Setting', 'Feature',
      'Version', 'Patch', 'Bug', 'Error', 'Crash', 'Reboot', 'Restart', 'Shutdown', 'Standby', 'Shortcut',
      'Dropdown', 'Checkbox', 'Slider', 'Toggle', 'Resolution', 'Bitmap', 'Vector', 'Rendering', 'Graphics', 'Animation',
      'Robot', 'Robotics', 'Automation', 'Machine', 'Data', 'Analytics', 'Pixel', 'Byte', 'Bit', 'Kilobyte',
      'Megabyte', 'Gigabyte', 'Terabyte', 'Binary', 'Digital', 'Analog', 'Signal', 'Frequency', 'Bandwidth', 'Protocol',
      'Domain', 'Portal', 'Platform', 'Simulation', 'Virtual', 'Reality', 'Gaming', 'Avatar', 'Multiplayer', 'Emoji',
      'Hacker', 'Coder', 'Programmer', 'Technician', 'Engineer',
    ],
  },
  {
    themeId: 'geography',
    words: [
      'Continent', 'Country', 'Nation', 'Capital', 'Border', 'Territory', 'Region', 'Province', 'State', 'District',
      'Island', 'Peninsula', 'Archipelago', 'Isthmus', 'Strait', 'Channel', 'Bay', 'Gulf', 'Cove', 'Lagoon',
      'Delta', 'Estuary', 'Fjord', 'Coastline', 'Shoreline', 'Cliff', 'Volcano', 'Glacier', 'Iceberg', 'Canyon',
      'Valley', 'Plateau', 'Plain', 'Prairie', 'Steppe', 'Desert', 'Oasis', 'Dune', 'Rainforest', 'Jungle',
      'Savanna', 'Tundra', 'Taiga', 'Wetland', 'Marsh', 'Swamp', 'Lake', 'River', 'Stream', 'Waterfall',
      'Spring', 'Reservoir', 'Basin', 'Mountain', 'Summit', 'Peak', 'Ridge', 'Highland', 'Lowland', 'Foothill',
      'Crater', 'Cave', 'Cavern', 'Equator', 'Hemisphere', 'Latitude', 'Longitude', 'Meridian', 'Timezone', 'Compass',
      'Atlas', 'Globe', 'Map', 'Cartography', 'Landscape', 'Terrain', 'Ecosystem', 'Climate', 'Population', 'Metropolis',
      'Village', 'Town', 'City', 'Suburb', 'Skyline', 'Landmark', 'Monument', 'Harbor', 'Port', 'Pier',
      'Frontier', 'Homeland', 'Colony', 'Settlement', 'Civilization', 'Culture', 'Language', 'Currency', 'Flag', 'Passport',
      'Expedition', 'Explorer', 'Voyage', 'Pilgrimage', 'Journey', 'Trek', 'Wilderness', 'Habitat', 'Biosphere', 'Everest',
      'Amazon', 'Nile', 'Sahara', 'Andes', 'Alps', 'Arctic', 'Antarctica', 'Pacific', 'Atlantic', 'Himalaya',
      'Rockies', 'Danube', 'Volga', 'Ganges', 'Mekong', 'Gobi', 'Kalahari', 'Serengeti', 'Pyrenees', 'Urals',
      'Mediterranean', 'Caribbean', 'Baltic', 'Adriatic', 'Aegean', 'Amazonia', 'Patagonia', 'Yukon', 'Siberia', 'Scandinavia',
      'Polynesia', 'Caucasus', 'Balkans', 'Iberia', 'Sicily', 'Corsica', 'Sardinia', 'Madagascar', 'Galapagos', 'Kilimanjaro',
      'Fuji', 'Etna', 'Vesuvius',
    ],
  },
  {
    themeId: 'fantasy',
    words: [
      'Dragon', 'Phoenix', 'Wizard', 'Witch', 'Sorcerer', 'Sorceress', 'Knight', 'Castle', 'Kingdom', 'Throne',
      'Crown', 'Sword', 'Shield', 'Armor', 'Quest', 'Legend', 'Myth', 'Giant', 'Troll', 'Goblin',
      'Elf', 'Dwarf', 'Mermaid', 'Unicorn', 'Centaur', 'Griffin', 'Sphinx', 'Oracle', 'Prophecy', 'Enchantment',
      'Spell', 'Potion', 'Wand', 'Cauldron', 'Curse', 'Charm', 'Amulet', 'Portal', 'Realm', 'Fortress',
      'Dungeon', 'Treasure', 'Wizardry', 'Magic', 'Magician', 'Alchemy', 'Alchemist', 'Fairy', 'Pixie', 'Gnome',
      'Ogre', 'Werewolf', 'Vampire', 'Zombie', 'Ghost', 'Ghoul', 'Specter', 'Phantom', 'Shadow', 'Warlock',
      'Necromancer', 'Paladin', 'Bard', 'Ranger', 'Rogue', 'Barbarian', 'Monk', 'Sorcery', 'Illusion', 'Talisman',
      'Relic', 'Rune', 'Scroll', 'Grimoire', 'Familiar', 'Broomstick', 'Elixir', 'Antidote', 'Herbalist', 'Druid',
      'Mythical', 'Legendary', 'Folklore', 'Fable', 'Fairytale', 'Storyteller', 'Minstrel', 'Jester', 'Herald', 'Squire',
      'Knighthood', 'Chivalry', 'Tournament', 'Joust', 'Duel', 'Warrior', 'Champion', 'Hero', 'Heroine', 'Villain',
      'Nemesis', 'Adventure', 'Odyssey', 'Saga', 'Chronicle', 'Seer', 'Fortune', 'Destiny', 'Fate', 'Blessing',
      'Ritual', 'Ceremony', 'Ancient', 'Mystic', 'Mystical', 'Mysterious', 'Enigma', 'Riddle', 'Labyrinth', 'Maze',
      'Vault', 'Chamber', 'Chest', 'Gem', 'Jewel', 'Crystal', 'Gemstone', 'Diamond', 'Ruby', 'Emerald',
      'Sapphire', 'Pearl', 'Scepter', 'Orb', 'Chalice', 'Goblet', 'Banner', 'Pennant', 'Emblem', 'Crest',
      'Insignia', 'Tower', 'Turret', 'Rampart', 'Moat', 'Drawbridge', 'Battlement', 'Stronghold', 'Citadel', 'Palace',
      'Manor', 'Empire', 'Dynasty', 'Monarch', 'Sovereign', 'Regent', 'Heir', 'Princess', 'Prince', 'King',
      'Queen', 'Duke', 'Duchess', 'Baron', 'Baroness', 'Noble', 'Peasant', 'Serf', 'Vassal',
    ],
  },
];

export default en;
