import type { WordSearchThemeSeed } from '../../engine/seedCorpus';

const es: WordSearchThemeSeed[] = [
  {
    themeId: 'animales',
    words: [
      'Perro', 'Gato', 'Caballo', 'Vaca', 'Oveja', 'Cabra', 'Cerdo', 'Burro', 'Camello', 'Llama',
      'Tigre', 'Leon', 'Pantera', 'Jaguar', 'Leopardo', 'Guepardo', 'Lobo', 'Zorro', 'Oso', 'Panda',
      'Mapache', 'Castor', 'Nutria', 'Ciervo', 'Corzo', 'Bisonte', 'Bufalo', 'Cebra', 'Niu', 'Elefante',
      'Rinoceronte', 'Hipopotamo', 'Mono', 'Gorila', 'Chimpance', 'Lemur', 'Serpiente', 'Lagarto', 'Rana', 'Sapo',
      'Tortuga', 'Aguila', 'Halcon', 'Buho', 'Paloma', 'Cuervo', 'Urraca', 'Cisne', 'Gaviota', 'Garza',
      'Marta', 'Tejon', 'Erizo', 'Topo', 'Murcielago', 'Osopolar', 'Morsa', 'Foca', 'Delfin', 'Tiburon',
      'Bacalao', 'Trucha', 'Salmon', 'Pulpo', 'Cangrejo', 'Camaron', 'Hormiga', 'Avispa', 'Abeja', 'Libelula',
      'Buitre', 'Pavo', 'Faisan', 'Perdiz', 'Gallina', 'Gallo', 'Pato', 'Ganso', 'Flamenco', 'Pelicano',
      'Camaleon', 'Iguana', 'Piton', 'Boa', 'Vibora', 'Escorpion', 'Arana', 'Tarantula', 'Termita', 'Saltamontes',
      'Escarabajo', 'Mariposa', 'Polilla', 'Caballitodemar', 'Raya', 'Atun', 'Caballa', 'Sardina', 'Ostra', 'Mejillon',
      'Loro', 'Pinguino', 'Avestruz', 'Gorrion', 'Petirrojo', 'Pavoreal', 'Tucan', 'Ciguena', 'Grulla',
      'Cocodrilo', 'Caiman', 'Gecko', 'Cobra', 'Mamba',
      'Anguila', 'Calamar', 'Langosta', 'Medusa', 'Orca', 'Toro', 'Arenque', 'Estrellamar', 'Almeja',
      'Luciernaga', 'Mosquito', 'Oruga', 'Pulga', 'Avispon', 'Abejorro', 'Cucaracha',
    ],
  },
  {
    themeId: 'comida',
    words: [
      'Manzana', 'Pera', 'Platano', 'Mango', 'Kiwi', 'Uva', 'Cereza', 'Ciruela', 'Melocoton', 'Albaricoque',
      'Fresa', 'Frambuesa', 'Mora', 'Arandano', 'Limon', 'Lima', 'Naranja', 'Mandarina', 'Pomelo', 'Aguacate',
      'Coco', 'Sandia', 'Pina', 'Papaya', 'Higo', 'Melon', 'Datil', 'Guayaba', 'Granada',
      'Zanahoria', 'Patata', 'Cebolla', 'Ajo', 'Guisante', 'Frijol', 'Maiz', 'Brocoli', 'Espinaca', 'Lechuga',
      'Col', 'Tomate', 'Pepino', 'Pimiento', 'Seta', 'Apio', 'Puerro', 'Calabaza', 'Calabacin', 'Coliflor',
      'Esparrago', 'Remolacha', 'Rabano', 'Lenteja', 'Berenjena',
      'Tarta', 'Sopa', 'Estofado', 'Tostada', 'Ensalada', 'Pasta', 'Pizza', 'Curry', 'Filete', 'Hamburguesa',
      'Bocadillo', 'Crepe', 'Gofre', 'Magdalena', 'Galleta', 'Dona', 'Brownie', 'Fideos', 'Pan', 'Tortilla',
      'Salchicha', 'Pudin', 'Granola', 'Croissant', 'Sushi', 'Taco', 'Risotto', 'Lasana', 'Kebab', 'Paella',
      'Ramen', 'Bagel', 'Falafel', 'Nachos', 'Dumpling',
      'Jamon', 'Huevo', 'Arroz', 'Ternera', 'Cordero', 'Miel', 'Mermelada', 'Queso', 'Mantequilla', 'Leche',
      'Yogur', 'Nata', 'Infusion', 'Cafe', 'Zumo', 'Chocolate', 'Jengibre', 'Azucar', 'Harina', 'Sirope',
      'Vainilla', 'Canela', 'Albahaca', 'Menta', 'Smoothie', 'Tofu', 'Agua', 'Limonada', 'Batido', 'Cacao',
      'Sidra', 'Aceite', 'Sal', 'Avena',
    ],
  },
  {
    themeId: 'naturaleza',
    words: [
      'Rosa', 'Tulipan', 'Girasol', 'Margarita', 'Lavanda', 'Lirio', 'Orquidea', 'Amapola', 'Iris', 'Violeta',
      'Clavel', 'Dalia', 'Narciso', 'Jazmin', 'Hibisco', 'Magnolia', 'Campanilla', 'Primula', 'Ranunculo', 'Brezo',
      'Trebol', 'Lila', 'Peonia', 'Glicina', 'Dedalera',
      'Roble', 'Abedul', 'Arce', 'Sauce', 'Pino', 'Palmera', 'Abeto', 'Haya', 'Cedro', 'Olmo',
      'Fresno', 'Alamo', 'Cipres', 'Alerce', 'Sequoia', 'Platano',
      'Helecho', 'Hiedra', 'Cactus', 'Aloe', 'Ortiga', 'Cardo', 'Musgo', 'Bambu', 'Vid', 'Arbol',
      'Lluvia', 'Nieve', 'Tormenta', 'Trueno', 'Relampago', 'Niebla', 'Nube', 'Viento', 'Helada', 'Granizo',
      'Hielo', 'Arcoiris', 'Ventisca', 'Tornado', 'Huracan', 'Llovizna', 'Neblina', 'Brisa', 'Copo', 'Aurora',
      'Sol',
      'Bosque', 'Rio', 'Lago', 'Montana', 'Valle', 'Playa', 'Desierto', 'Oceano', 'Acantilado', 'Cueva',
      'Cascada', 'Isla', 'Prado', 'Glaciar', 'Volcan', 'Selva', 'Canon', 'Pantano', 'Estepa', 'Duna',
      'Estanque', 'Arroyo', 'Marisma', 'Laguna', 'Arrecife', 'Meseta', 'Sabana', 'Tundra', 'Fiordo', 'Bahia',
      'Garganta', 'Cresta', 'Cima', 'Cala', 'Grava',
      'Primavera', 'Verano', 'Otono', 'Invierno', 'Amanecer', 'Anochecer', 'Eclipse', 'Marea', 'Brillo', 'Polen',
      'Tierra',
    ],
  },
  {
    themeId: 'deportes',
    words: [
      'Futbol', 'Balonmano', 'Baloncesto', 'Voleibol', 'Hockey', 'Tenis', 'Badminton', 'Squash', 'Rugby', 'Beisbol',
      'Softbol', 'Atletismo', 'Sprint', 'Maraton', 'Triatlon', 'Natacion', 'Waterpolo', 'Buceo', 'Esgrima', 'Judo',
      'Karate', 'Taekwondo', 'Boxeo', 'Lucha', 'Gimnasia', 'Golf', 'Cricket', 'Esqui', 'Snowboard', 'Patinaje',
      'Curling', 'Remo', 'Vela', 'Surf', 'Kitesurf', 'Windsurf', 'Piraguismo', 'Kayak', 'Tiroconarco', 'Dardos',
      'Billar', 'Snooker', 'Esports', 'Halterofilia', 'Equitacion', 'Senderismo', 'Escalada', 'Ciclismo', 'Mountainbike', 'Trote',
      'Raqueta', 'Casco', 'Guantes', 'Bate', 'Palo', 'Red', 'Meta', 'Aro', 'Puck', 'Flecha',
      'Arco', 'Colchoneta', 'Pista', 'Silbato', 'Trofeo', 'Medalla', 'Pala', 'Cuerda', 'Esquis', 'Camiseta',
      'Tacos',
    ],
  },
  {
    themeId: 'ropa',
    words: [
      'Camiseta', 'Sueter', 'Chaleco', 'Chaqueta', 'Blusa', 'Camisa', 'Polo', 'Top', 'Pantalon', 'Vaqueros',
      'Leggings', 'Falda', 'Vestido', 'Short', 'Pijama', 'Calzoncillo', 'Sosten', 'Calcetines', 'Medias', 'Gorro',
      'Bufanda', 'Gorra', 'Sombrero', 'Zapatillas', 'Botas', 'Sandalias', 'Tacones', 'Chanclas', 'Cinturon', 'Bikini',
      'Banador', 'Mono', 'Traje', 'Americana', 'Blazer', 'Sudadera', 'Poncho', 'Kimono', 'Chandal', 'Pantaloncorto',
      'Deportiva', 'Camisadevestir', 'Abrigo', 'Mediaslargas', 'Impermeable', 'Parka', 'Jersey', 'Cardigan',
      'Collar', 'Pulsera', 'Pendiente', 'Reloj', 'Gafas', 'Bolso', 'Cartera', 'Paraguas', 'Diadema', 'Corbata',
      'Corbatin', 'Lazo',
      'Algodon', 'Seda', 'Lana', 'Lino', 'Denim', 'Terciopelo', 'Cuero', 'Poliester', 'Nylon', 'Polar',
      'Cachemira', 'Saten', 'Ante',
    ],
  },
  {
    themeId: 'transporte',
    words: [
      'Coche', 'Bus', 'Bicicleta', 'Moto', 'Scooter', 'Patinete', 'Tractor', 'Montacargas', 'Ambulancia', 'Taxi',
      'Limusina', 'Autocaravana', 'Caravana', 'Tren', 'Metro', 'Tranvia', 'Monorail', 'Barco', 'Velero', 'Lancha',
      'Submarino', 'Avion', 'Helicoptero', 'Zeppelin', 'Dron', 'Naveespacial', 'Quad', 'Motonieve', 'Tanque',
      'Bulldozer', 'Excavadora', 'Camiongrua', 'Hormigonera', 'Cochedegolf', 'Segway', 'Hovercraft', 'Motosacuatica', 'Lancharapida', 'Kart',
      'Bicicarguera', 'Camion', 'Minivan', 'Cabrio', 'Coupe', 'Sedan', 'Roadster',
    ],
  },
  {
    themeId: 'hogar',
    words: [
      'Cuchillo', 'Tenedor', 'Cuchara', 'Espatula', 'Batidor', 'Pinzas', 'Pelador', 'Rallador', 'Colador', 'Bascula',
      'Sarten', 'Wok', 'Cazo', 'Batidora', 'Tostadora', 'Hervidor', 'Microondas', 'Horno', 'Cocina', 'Parrilla',
      'Cucharon', 'Bol', 'Plato', 'Taza', 'Bandeja', 'Rejilla', 'Cacillo', 'Vaso', 'Jarra', 'Olla',
      'Botella', 'Tetera', 'Congelador',
      'Dormitorio', 'Bano', 'Pasillo', 'Desvan', 'Sotano', 'Garaje', 'Jardin', 'Balcon', 'Estudio', 'Porche',
      'Terraza', 'Despensa', 'Cuarto', 'Salon',
      'Silla', 'Sofa', 'Mesa', 'Escritorio', 'Cama', 'Estante', 'Armario', 'Cajon', 'Lampara', 'Espejo',
      'Alfombra', 'Cortina', 'Cojin', 'Manta', 'Libreria', 'Sillon', 'Taburete', 'Comoda', 'Chimenea', 'Aparador',
      'Mesita', 'Cuadro', 'Florero', 'Felpudo',
      'Nevera', 'Lavadora', 'Secadora', 'Aspiradora', 'Lavavajillas', 'Television', 'Calefactor', 'Ventilador', 'Radio', 'Plancha',
      'Impresora', 'Laptop', 'Telefono',
      'Escoba', 'Fregona', 'Cubo', 'Toalla', 'Jabon', 'Vela', 'Reloj', 'Puerta', 'Ventana', 'Llave',
      'Ducha', 'Banera', 'Cesta', 'Percha', 'Esponja',
      'Pala', 'Azada', 'Rastrillo', 'Azadon', 'Paleta', 'Carretilla', 'Aspersor', 'Manguera', 'Invernadero', 'Cobertizo',
      'Valla', 'Seto', 'Arbusto', 'Cesped', 'Maceta', 'Jardinera', 'Compost', 'Mantillo', 'Podadora', 'Escalera',
      'Enrejado', 'Bebedero', 'Sendero',
    ],
  },
  {
    themeId: 'espacio',
    words: [
      'Espacio', 'Universo', 'Cosmos', 'Estrella', 'Planeta', 'Luna', 'Sol', 'Cometa', 'Meteoro',
      'Vialactea', 'Nebulosa', 'Cumulo', 'Supernova', 'Agujeronegro', 'Galaxia', 'Cuasar', 'Pulsar', 'Vacio',
      'Naveespacial', 'Cohete', 'Transbordador', 'Satelite', 'Telescopio', 'Observatorio', 'Astronauta', 'Cosmonauta', 'Estacion', 'Orbita',
      'Trayectoria', 'Gravedad', 'Anoluz', 'Constelacion', 'Horizonte', 'Atmosfera', 'Exoplaneta', 'Oscuridad',
      'Plasma', 'Materia', 'Antimateria', 'Radiacion', 'Vientosolar', 'Llamaradasolar', 'Crater', 'Nucleo', 'Manto',
    ],
  },
  {
    themeId: 'profesiones',
    words: [
      'Medico', 'Enfermero', 'Carpintero', 'Fontanero', 'Electricista', 'Panadero', 'Carnicero', 'Cocinero', 'Piloto', 'Conductor',
      'Bombero', 'Policia', 'Abogado', 'Juez', 'Notario', 'Pintor', 'Albanil', 'Arquitecto', 'Ingeniero', 'Programador',
      'Disenador', 'Periodista', 'Escritor', 'Poeta', 'Actor', 'Cantante', 'Musico', 'Jardinero', 'Granjero', 'Peluquero',
      'Mecanico', 'Recepcionista', 'Entrenador', 'Coach', 'Maestro', 'Profesor', 'Vendedor', 'Barista', 'Camarero', 'Farmaceutico',
      'Laboratorista', 'Cuidador', 'Terapeuta', 'Psicologo', 'Interprete', 'Traductor', 'Fotografo', 'Artista', 'Yesero', 'Optico',
    ],
  },
  {
    themeId: 'familia',
    words: [
      'Padre', 'Madre', 'Hijo', 'Hija', 'Hermano', 'Hermana', 'Abuelo', 'Abuela', 'Tio', 'Tia',
      'Sobrino', 'Sobrina', 'Padrino', 'Madrina', 'Ahijado', 'Suegro', 'Suegra', 'Yerno', 'Nuera', 'Cunado',
      'Cunada', 'Padrastro', 'Madrastra', 'Hermanastro', 'Hermanastra', 'Hogar', 'Familia',
      'Nieto', 'Primo', 'Nieta', 'Gemelo', 'Gemela', 'Novio', 'Novia', 'Esposo', 'Esposa', 'Pareja',
      'Prometido', 'Descendiente', 'Ancestro', 'Linaje', 'Nino', 'Bebe', 'Pequeno', 'Adolescente', 'Adulto', 'Mayor',
    ],
  },
  {
    themeId: 'emociones',
    words: [
      'Feliz', 'Enojado', 'Asustado', 'Triste', 'Orgulloso', 'Calmo', 'Nervioso', 'Contento', 'Decepcionado', 'Sorprendido',
      'Irritado', 'Relajado', 'Indefenso', 'Seguro', 'Solitario', 'Alegre', 'Sombrio', 'Furioso', 'Emocionado', 'Sereno',
      'Preocupado', 'Aliviado', 'Confuso', 'Encantado', 'Divertido', 'Frustrado', 'Esperanzado', 'Desesperado', 'Agradecido', 'Curioso',
      'Avergonzado', 'Culpable', 'Timido', 'Inquieto', 'Panico', 'Rabioso', 'Satisfecho', 'Conmovido', 'Animado', 'Reacio',
      'Asco', 'Envidia', 'Celos', 'Arrepentido', 'Asombrado', 'Horrorizado', 'Aturdido', 'Euforico', 'Melancolico', 'Carinoso',
    ],
  },
  {
    themeId: 'cualidades',
    words: [
      'Amable', 'Listo', 'Fuerte', 'Valiente', 'Honesto', 'Creativo', 'Paciente', 'Servicial', 'Amistoso', 'Atento',
      'Tranquilo', 'Genial', 'Gracioso', 'Serio', 'Fiable', 'Ambicioso', 'Sociable', 'Preciso', 'Flexible', 'Ingenioso',
      'Modesto', 'Sincero', 'Decidido', 'Optimista', 'Pesimista', 'Carismatico', 'Curioso', 'Dedicado', 'Observador', 'Leal',
      'Dulce', 'Estricto', 'Sensible', 'Calmado', 'Fogoso', 'Ordenado', 'Caotico', 'Alegre', 'Prudente', 'Logico',
      'Empatico', 'Practico', 'Enfocado', 'Habil', 'Resuelto', 'Integro', 'Autonomo', 'Cuidadoso', 'Audaz', 'Energetico',
    ],
  },
  {
    themeId: 'pasatiempos',
    words: [
      'Dibujar', 'Pintar', 'Leer', 'Escribir', 'Ciclismo', 'Caminar', 'Nadar', 'Cocinar', 'Hornear', 'Tejer',
      'Ganchillo', 'Jugar', 'Pescar', 'Cantar', 'Bailar', 'Jardineria', 'Acampar', 'Viajar', 'Correr', 'Patinar',
      'Esquiar', 'Yoga', 'Meditacion', 'Boulder', 'Escalar', 'Fotografia', 'Filmar', 'Editar', 'Bordar', 'Carpinteria',
      'Modelismo', 'Coleccionar', 'Ajedrez', 'Cartas', 'Puzles', 'Caligrafia', 'Actuar', 'Tambor',
      'Elaborar', 'Manualidades', 'Forjar', 'Esculpir', 'Ceramica',
      'Grabar', 'Hilar', 'Colorear', 'Malabares', 'Asar', 'Tostar', 'Sazonar', 'Ebanisteria',
      'Soldar', 'Programar', 'Bloguear', 'Vloguear', 'Transmitir', 'Fitness',
    ],
  },
  {
    themeId: 'herramientas',
    words: [
      'Martillo', 'Sierra', 'Cincel', 'Lima', 'Tenazas', 'Alicate', 'Nivel', 'Cintametrica', 'Metro', 'Destornillador',
      'Phillips', 'Plano', 'Llavefija', 'Llavevaso', 'Llaveinglesa', 'Cuter', 'Tijeras', 'Pistolacola', 'Grapadora', 'Soldador',
      'Taladro', 'Lijadora', 'Amoladora', 'Fresadora', 'Cortatubos', 'Rascador', 'Brocha', 'Rodillo',
      'Paleta', 'Brocamadera', 'Brocametal', 'Abrazadera', 'Sierramanual', 'Mazo', 'Martillogarra',
      'Multitool', 'Pelacables', 'Cortaalambre', 'Pistolacalor', 'Desbarbador', 'Cepillo',
    ],
  },
  {
    themeId: 'electronica',
    words: [
      'Laptop', 'Tablet', 'Smartphone', 'Computadora', 'Monitor', 'Teclado', 'Raton', 'Headset', 'Auriculares', 'Altavoz',
      'Microfono', 'Camara', 'Router', 'Modem', 'Impresora', 'Escaner', 'Television', 'Proyector', 'Controlador', 'Consola',
      'Smartwatch', 'Cargador', 'Powerbank', 'Usbstick', 'Discoduro', 'Ssd', 'Dron', 'Webcam', 'Pantalla', 'Tarjetasonido',
      'Placamadre', 'Procesador', 'Tarjetagrafica', 'Adaptador', 'Bateria', 'Sensor', 'Bluetooth', 'Wifi', 'Ethernet', 'Microchip',
    ],
  },
  {
    themeId: 'colores',
    words: [
      'Rojo', 'Amarillo', 'Blanco', 'Rosa', 'Gris', 'Dorado', 'Ocre', 'Lila', 'Crema', 'Aqua',
      'Jade', 'Salmon', 'Azul', 'Verde', 'Marron', 'Oxido', 'Ambar', 'Oliva', 'Malva', 'Cyan',
      'Marfil', 'Beige', 'Bronce', 'Cobre', 'Morado', 'Negro', 'Azur', 'Taupe', 'Crudo', 'Sepia',
      'Violeta', 'Coral', 'Indigo', 'Cobalto', 'Plata', 'Naranja', 'Marino', 'Mostaza', 'Lavanda', 'Turquesa',
      'Magenta', 'Fucsia', 'Carmesi', 'Antracita', 'Burdeos', 'Castano', 'Menta', 'Pastel', 'Terracota', 'Arena',
    ],
  },
  {
    themeId: 'cuerpo',
    words: [
      'Ojo', 'Oreja', 'Brazo', 'Pierna', 'Cadera', 'Mandibula', 'Dedo', 'Costilla', 'Labio', 'Encia',
      'Espinilla', 'Rodilla', 'Nariz', 'Espalda', 'Cuello', 'Talon', 'Mano', 'Pie', 'Una', 'Pelo',
      'Piel', 'Hueso', 'Barbilla', 'Ceja', 'Palma', 'Pantorrilla', 'Muneca', 'Tobillo', 'Pulgar', 'Codo',
      'Mejilla', 'Pecho', 'Columna', 'Muslo', 'Craneo', 'Corazon', 'Barriga', 'Cerebro', 'Diente', 'Menique',
      'Sien', 'Lengua', 'Axila', 'Rinon', 'Musculo', 'Parpado', 'Hombro', 'Estomago', 'Frente', 'Rotula',
    ],
  },
  {
    themeId: 'escuela',
    words: [
      'Boligrafo', 'Tinta', 'Libro', 'Escritorio', 'Pegamento', 'Cinta', 'Examen', 'Test', 'Quiz', 'Pizarra',
      'Regla', 'Tiza', 'Pintura', 'Globo', 'Atlas', 'Clase', 'Nota', 'Puntuacion', 'Almuerzo', 'Estudio',
      'Lapiz', 'Carpeta', 'Archivador', 'Grapa', 'Crayola', 'Goma', 'Rotulador', 'Taquilla', 'Leccion', 'Recreo',
      'Diario', 'Compas', 'Paleta', 'Armario', 'Escaner', 'Cuaderno', 'Mochila', 'Tijeras', 'Manual', 'Ejercicio',
      'Tarea', 'Agenda', 'Horario', 'Biblioteca', 'Aula', 'Profesor', 'Alumno', 'Ciencia', 'Historia', 'Musica',
    ],
  },
  {
    themeId: 'musica',
    words: [
      'Tambor', 'Guitarra', 'Piano', 'Violin', 'Trompeta', 'Flauta', 'Arpa', 'Chelo', 'Tuba', 'Trombon',
      'Clarinete', 'Acordeon', 'Ukulele', 'Banjo', 'Saxofon', 'Teclado', 'Xilofono', 'Campana', 'Platillo', 'Gong',
      'Bajo', 'Pandereta', 'Armonica', 'Viola', 'Triangulo', 'Gaita', 'Sintetizador', 'Microfono', 'Clavecin',
      'Ritmo', 'Melodia', 'Acorde', 'Armonia', 'Tempo', 'Tono', 'Concierto', 'Album', 'Cancion', 'Cantante',
      'Banda', 'Solo', 'Duo', 'Orquesta', 'Acustico', 'Letra', 'Estrofa', 'Puente', 'Riff', 'Groove',
      'Remix', 'Pista', 'Encore', 'Voz', 'Coro', 'Ensayo', 'Festival', 'Escenario', 'Compositor', 'Director',
      'Volumen',
      'Jazz', 'Blues', 'Rock', 'Pop', 'Clasica', 'Folk', 'Reggae', 'Gospel', 'Opera', 'Rap',
      'Soul', 'Country', 'Funk', 'Disco', 'Punk', 'Metal', 'Techno', 'Indie', 'Balada', 'Danza',
      'Swing', 'Vals', 'Grunge', 'Electro', 'Latino', 'Bluegrass', 'Celta',
      'Altavoz', 'Auriculares', 'Vinilo', 'Casete', 'Tocadiscos', 'Estereo', 'Jukebox', 'Karaoke', 'Podcast',
      'Mezclador',
    ],
  },
];

export default es;
