import type { WordSearchThemeSeed } from '../../engine/seedCorpus';

const fr: WordSearchThemeSeed[] = [
  {
    themeId: 'animaux',
    words: [
      'Chien', 'Chat', 'Cheval', 'Vache', 'Mouton', 'Chevre', 'Cochon', 'Ane', 'Chameau', 'Lama',
      'Tigre', 'Lion', 'Panthere', 'Jaguar', 'Leopard', 'Guepard', 'Loup', 'Renard', 'Ours', 'Panda',
      'Ratonlaveur', 'Castor', 'Loutre', 'Cerf', 'Chevreuil', 'Bison', 'Buffle', 'Zebre', 'Gnou', 'Elephant',
      'Rhinoceros', 'Hippopotame', 'Singe', 'Gorille', 'Chimpanze', 'Lemur', 'Serpent', 'Lezard', 'Grenouille', 'Crapaud',
      'Tortue', 'Aigle', 'Faucon', 'Hibou', 'Colombe', 'Corbeau', 'Pie', 'Cygne', 'Mouette', 'Heron',
      'Martre', 'Blaireau', 'Herisson', 'Taupe', 'Chauvesouris', 'Morse', 'Phoque', 'Dauphin', 'Requin', 'Baleine',
      'Cabillaud', 'Truite', 'Saumon', 'Poulpe', 'Crabe', 'Crevette', 'Fourmi', 'Guepe', 'Abeille', 'Libellule',
      'Vautour', 'Dinde', 'Faisan', 'Perdrix', 'Coq', 'Canard', 'Oie', 'Flamant', 'Pelican', 'Cameleon',
      'Iguane', 'Python', 'Boa', 'Vipere', 'Scorpion', 'Araignee', 'Tarentule', 'Termite', 'Sauterelle', 'Scarabee',
      'Papillon', 'Mite', 'Hippocampe', 'Raie', 'Thon', 'Maquereau', 'Sardine', 'Huitre', 'Moule', 'Anguille',
      'Perroquet', 'Pingouin', 'Autruche', 'Moineau', 'Rougegorge', 'Paon', 'Toucan', 'Cigogne', 'Grue', 'Crocodile',
      'Alligator', 'Gecko', 'Cobra', 'Mamba', 'Calmar', 'Homard', 'Meduse', 'Orque', 'Hareng', 'Etoilemer',
      'Palourde', 'Luciole', 'Moustique', 'Chenille', 'Puce', 'Frelon', 'Bourdon', 'Cafard',
    ],
  },
  {
    themeId: 'nourriture',
    words: [
      'Pomme', 'Poire', 'Banane', 'Mangue', 'Kiwi', 'Raisin', 'Cerise', 'Prune', 'Peche', 'Abricot',
      'Fraise', 'Framboise', 'Mure', 'Myrtille', 'Citron', 'Citronvert', 'Orange', 'Mandarine', 'Pamplemousse', 'Avocat',
      'Coco', 'Pasteque', 'Ananas', 'Papaye', 'Figue', 'Canneberge', 'Melon', 'Datte', 'Goyave', 'Grenade',
      'Patate', 'Oignon', 'Ail', 'Pois', 'Haricot', 'Mais', 'Brocoli', 'Epinard', 'Laitue', 'Chou',
      'Tomate', 'Concombre', 'Poivron', 'Champignon', 'Celeri', 'Poireau', 'Courge', 'Courgette', 'Choufleur', 'Asperge',
      'Betterave', 'Radis', 'Lentille', 'Aubergine', 'Tarte', 'Soupe', 'Ragout', 'Tartine', 'Salade', 'Pates',
      'Pizza', 'Curry', 'Steak', 'Burger', 'Sandwich', 'Crepe', 'Gaufre', 'Muffin', 'Gateau', 'Beignet',
      'Brownie', 'Nouilles', 'Pain', 'Omelette', 'Saucisse', 'Pudding', 'Granola', 'Brioche', 'Croissant', 'Sushi',
      'Taco', 'Risotto', 'Lasagne', 'Kebab', 'Paella', 'Ramen', 'Bagel', 'Falafel', 'Nachos', 'Ravioli',
      'Jambon', 'Oeuf', 'Riz', 'Boeuf', 'Porc', 'Agneau', 'Miel', 'Confiture', 'Fromage', 'Beurre',
      'Lait', 'Yaourt', 'Creme', 'The', 'Cafe', 'Jus', 'Chocolat', 'Gingembre', 'Sucre', 'Farine',
      'Sirop', 'Vanille', 'Cannelle', 'Basilic', 'Menthe', 'Smoothie', 'Tofu', 'Eau', 'Limonade', 'Milkshake',
      'Cacao', 'Cidre', 'Huile', 'Sel', 'Flocons',
    ],
  },
  {
    themeId: 'nature',
    words: [
      'Rose', 'Tulipe', 'Tournesol', 'Paquerette', 'Lavande', 'Lys', 'Orchidee', 'Coquelicot', 'Iris', 'Pensee',
      'Oeillet', 'Dahlia', 'Narcisse', 'Jasmin', 'Hibiscus', 'Magnolia', 'Jacinthe', 'Jonquille', 'Primevere', 'Renoncule',
      'Bruyere', 'Trefle', 'Lilas', 'Pivoine', 'Glycine', 'Digitale', 'Chene', 'Bouleau', 'Erable', 'Saule',
      'Pin', 'Palmier', 'Sapin', 'Hetre', 'Cedre', 'Orme', 'Frene', 'Peuplier', 'Cypres', 'Meleze',
      'Sequoia', 'Platane', 'Fougere', 'Lierre', 'Cactus', 'Aloe', 'Pissenlit', 'Ortie', 'Chardon', 'Mousse',
      'Bambou', 'Vigne', 'Pluie', 'Neige', 'Tempete', 'Tonnerre', 'Foudre', 'Brouillard', 'Nuage', 'Vent',
      'Gelee', 'Grele', 'Glace', 'Arcenciel', 'Blizzard', 'Tornade', 'Ouragan', 'Bruine', 'Brume', 'Brise',
      'Flocon', 'Aurore', 'Soleil', 'Foret', 'Riviere', 'Lac', 'Montagne', 'Vallee', 'Plage', 'Desert',
      'Ocean', 'Falaise', 'Grotte', 'Cascade', 'Ile', 'Prairie', 'Glacier', 'Volcan', 'Jungle', 'Canyon',
      'Marais', 'Steppe', 'Dune', 'Etang', 'Ruisseau', 'Lande', 'Lagune', 'Recif', 'Plateau', 'Savane',
      'Toundra', 'Fjord', 'Baie', 'Gorge', 'Crete', 'Sommet', 'Crique', 'Galet', 'Printemps', 'Ete',
      'Automne', 'Hiver', 'Lever', 'Coucher', 'Eclipse', 'Maree', 'Pollen', 'Terre',
    ],
  },
  {
    themeId: 'sports',
    words: [
      'Football', 'Handball', 'Basketball', 'Volleyball', 'Hockey', 'Tennis', 'Badminton', 'Squash', 'Rugby', 'Baseball',
      'Softball', 'Athletisme', 'Sprint', 'Marathon', 'Triathlon', 'Natation', 'Waterpolo', 'Plongee', 'Escrime', 'Judo',
      'Karate', 'Taekwondo', 'Boxe', 'Lutte', 'Gymnastique', 'Golf', 'Cricket', 'Ski', 'Snowboard', 'Patinage',
      'Curling', 'Aviron', 'Voile', 'Surf', 'Kitesurf', 'Windsurf', 'Canoe', 'Kayak', 'Tiralarc', 'Flechettes',
      'Billard', 'Snooker', 'Esports', 'Halterophilie', 'Equitation', 'Randonnee', 'Escalade', 'Cyclisme', 'Jogging', 'Luge',
      'Raquette', 'Casque', 'Gants', 'Batte', 'Crosse', 'Filet', 'But', 'Cerceau', 'Palet', 'Fleche',
      'Arc', 'Tapis', 'Terrain', 'Sifflet', 'Trophee', 'Medaille', 'Pagaie', 'Corde', 'Selle', 'Skis',
      'Maillot', 'Crampons',
    ],
  },
  {
    themeId: 'vetements',
    words: [
      'Tshirt', 'Pull', 'Gilet', 'Veste', 'Chemisier', 'Chemise', 'Polo', 'Debardeur', 'Pantalon', 'Jean',
      'Legging', 'Jupe', 'Robe', 'Short', 'Pyjama', 'Chaussettes', 'Collant', 'Bonnet', 'Echarpe', 'Casquette',
      'Chapeau', 'Baskets', 'Bottes', 'Sandales', 'Talons', 'Claquettes', 'Ceinture', 'Bikini', 'Maillotbain', 'Combinaison',
      'Costume', 'Blazer', 'Hoodie', 'Poncho', 'Kimono', 'Survetement', 'Tunique', 'Bas', 'Doudoune', 'Impermeable',
      'Manteauhiver', 'Parka', 'Sweat', 'Cardigan', 'Gants', 'Moufles', 'Giletsprt', 'Salopette', 'Robe', 'Kilt',
      'Collier', 'Bracelet', 'Boucle', 'Montre', 'Lunettes', 'Sac', 'Portefeuille', 'Parapluie', 'Bandeau', 'Cravate',
      'Noeud', 'Ruban', 'Coton', 'Soie', 'Laine', 'Lin', 'Denim', 'Velours', 'Cuir', 'Polyester',
      'Nylon', 'Polaire', 'Cachemire', 'Satin', 'Daim',
    ],
  },
  {
    themeId: 'transport',
    words: [
      'Voiture', 'Bus', 'Velo', 'Moto', 'Scooter', 'Trottinette', 'Tracteur', 'Ambulance', 'Taxi', 'Limousine',
      'Campingcar', 'Caravane', 'Train', 'Metro', 'Tram', 'Monorail', 'Bateau', 'Voilier', 'Motonaute', 'Sousmarin',
      'Avion', 'Helicoptere', 'Zeppelin', 'Drone', 'Vaisseau', 'Quad', 'Motoneige', 'Bulldozer', 'Pelleteuse', 'Camion',
      'Minivan', 'Cabriolet', 'Coupe', 'Berline', 'Roadster', 'Chariot', 'Segway', 'Hovercraft', 'Jetski', 'Kart',
      'Rickshaw', 'Cyclomoteur', 'Planeur', 'Traversier', 'Barge', 'Canoe', 'Kayak', 'Radeau', 'Charette', 'Luge',
    ],
  },
  {
    themeId: 'maison',
    words: [
      'Couteau', 'Fourchette', 'Cuillere', 'Spatule', 'Fouet', 'Pinces', 'Eplucheur', 'Rape', 'Passoire', 'Balance',
      'Poele', 'Wok', 'Casserole', 'Blender', 'Grille', 'Bouilloire', 'Microondes', 'Four', 'Fourneau', 'Grill',
      'Louche', 'Bol', 'Assiette', 'Tasse', 'Mixeur', 'Plateau', 'Verre', 'Pichet', 'Pot', 'Bouteille',
      'Theiere', 'Congelateur', 'Cuisine', 'Chambre', 'Salle', 'Couloir', 'Grenier', 'Cave', 'Garage', 'Jardin',
      'Balcon', 'Bureau', 'Veranda', 'Terrasse', 'Cellier', 'Nurserie', 'Salon', 'Chaise', 'Canape', 'Table',
      'Lit', 'Etagere', 'Armoire', 'Tiroir', 'Lampe', 'Miroir', 'Tapis', 'Rideau', 'Coussin', 'Couette',
      'Placard', 'Bibliotheque', 'Fauteuil', 'Tabouret', 'Commode', 'Cheminee', 'Buffet', 'Chevet', 'Cadre', 'Vase',
      'Paillasson', 'Frigo', 'Laveuse', 'Sechoir', 'Aspirateur', 'Television', 'Radiateur', 'Ventilateur', 'Radio', 'Fer',
      'Imprimante', 'Laptop', 'Telephone', 'Balai', 'Vadrouille', 'Seau', 'Serviette', 'Savon', 'Bougie', 'Horloge',
      'Porte', 'Fenetre', 'Cle', 'Douche', 'Baignoire', 'Panier', 'Cintre', 'Eponge', 'Pelle', 'Beche',
      'Rateau', 'Binette', 'Truelle', 'Brouette', 'Tondeuse', 'Arroseur', 'Tuyau', 'Serre', 'Cabane', 'Cloture',
      'Portail', 'Haie', 'Buisson', 'Pelouse', 'Jardiniere', 'Compost', 'Secateur', 'Echelle', 'Treille', 'Allee',
    ],
  },
  {
    themeId: 'espace',
    words: [
      'Espace', 'Univers', 'Cosmos', 'Etoile', 'Planete', 'Lune', 'Soleil', 'Comete', 'Meteore', 'Voielactee',
      'Nebuleuse', 'Amas', 'Supernova', 'Trounoir', 'Galaxie', 'Quasar', 'Pulsar', 'Vide', 'Vaisseau', 'Fusee',
      'Navette', 'Satellite', 'Telescope', 'Observatoire', 'Astronaute', 'Cosmonaute', 'Station', 'Orbite', 'Trajectoire', 'Gravite',
      'Anneelumiere', 'Constellation', 'Horizon', 'Atmosphere', 'Exoplanete', 'Obscurite', 'Plasma', 'Matiere', 'Antimatiere', 'Radiation',
      'Ventsolaire', 'Tempetesol', 'Cratere', 'Noyau', 'Manteau', 'Eclipse', 'Solstice', 'Zenith', 'Asteroide', 'Trounoir',
    ],
  },
  {
    themeId: 'metiers',
    words: [
      'Medecin', 'Infirmier', 'Charpentier', 'Plombier', 'Electricien', 'Boulanger', 'Boucher', 'Cuisinier', 'Pilote', 'Chauffeur',
      'Pompier', 'Policier', 'Avocat', 'Juge', 'Notaire', 'Peintre', 'Macon', 'Architecte', 'Ingenieur', 'Programmeur',
      'Designer', 'Journaliste', 'Ecrivain', 'Poete', 'Acteur', 'Chanteur', 'Musicien', 'Jardinier', 'Fermier', 'Coiffeur',
      'Mecanicien', 'Entraineur', 'Coach', 'Enseignant', 'Professeur', 'Vendeur', 'Barista', 'Serveur', 'Pharmacien', 'Laborantin',
      'Soignant', 'Therapeute', 'Psychologue', 'Interprete', 'Traducteur', 'Photographe', 'Artiste', 'Platrier', 'Opticien', 'Analyste',
    ],
  },
  {
    themeId: 'famille',
    words: [
      'Pere', 'Mere', 'Fils', 'Fille', 'Frere', 'Soeur', 'Papi', 'Mamie', 'Oncle', 'Tante',
      'Neveu', 'Niece', 'Parrain', 'Marraine', 'Filleul', 'Beaupere', 'Bellemere', 'Gendre', 'Bru', 'Beaufrere',
      'Bellesoeur', 'Cousin', 'Cousine', 'Demifrere', 'Demisoeur', 'Foyer', 'Famille', 'Petitfils', 'Petitefille', 'Jumeau',
      'Jumelle', 'Marie', 'Mariee', 'Epoux', 'Epouse', 'Partenaire', 'Fiance', 'Descendant', 'Ancetre', 'Enfant',
      'Bebe', 'Bambin', 'Ado', 'Adulte', 'Senior', 'Tuteur', 'Fratrie', 'Parent', 'Progenitur', 'Clan',
    ],
  },
  {
    themeId: 'emotions',
    words: [
      'Heureux', 'Fache', 'Peur', 'Triste', 'Fier', 'Calme', 'Nerveux', 'Joyeux', 'Decu', 'Surpris',
      'Agace', 'Detendu', 'Impuissant', 'Confiant', 'Seul', 'Gai', 'Sombre', 'Colere', 'Excite', 'Paisible',
      'Inquiet', 'Soulage', 'Confus', 'Charme', 'Amuse', 'Frustre', 'Desespere', 'Reconnaissant', 'Curieux', 'Honteux',
      'Coupable', 'Timide', 'Anxieux', 'Panique', 'Furieux', 'Satisfait', 'Emu', 'Ravi', 'Rebute', 'Degout',
      'Envie', 'Jalousie', 'Regret', 'Emerveille', 'Choque', 'Deconcerte', 'Euphorique', 'Melancolique', 'Affectueux', 'Espoir',
    ],
  },
  {
    themeId: 'loisirs',
    words: [
      'Dessiner', 'Peindre', 'Lire', 'Ecrire', 'Cyclisme', 'Marche', 'Nager', 'Cuisiner', 'Patisser', 'Tricoter',
      'Crocheter', 'Jouer', 'Pecher', 'Chanter', 'Danser', 'Jardiner', 'Camper', 'Voyager', 'Courir', 'Patiner',
      'Skier', 'Yoga', 'Meditation', 'Grimper', 'Photo', 'Filmer', 'Broder', 'Menuiserie', 'Modelisme', 'Collectionner',
      'Echecs', 'Cartes', 'Puzzler', 'Calligraphie', 'Tambouriner', 'Brasser', 'Bricoler', 'Forger', 'Sculpter', 'Poterie',
      'Graver', 'Tisser', 'Filer', 'Colorier', 'Jongler', 'Programmer', 'Bloguer', 'Streamer', 'Fitness', 'Souder',
    ],
  },
  {
    themeId: 'outils',
    words: [
      'Marteau', 'Scie', 'Ciseau', 'Lime', 'Pince', 'Niveau', 'Metre', 'Tournevis', 'Cutter', 'Ciseaux',
      'Agrafeuse', 'Perceuse', 'Ponceuse', 'Meuleuse', 'Fraiseuse', 'Coupetube', 'Etau', 'Grattoir', 'Pinceau', 'Rouleau',
      'Truelle', 'Spatule', 'Serrejoint', 'Sciesauteuse', 'Maillet', 'Multitool', 'Rabot', 'Burin', 'Perforateur', 'Visseuse',
      'Equerre', 'Trusquin', 'Compas', 'Alene', 'Pointeau', 'Taraud', 'Filiere', 'Rivet', 'Machefer', 'Poincon',
      'Levier', 'Crochet', 'Sangle', 'Ventouse', 'Detecteur', 'Decapeur', 'Ebarbeur', 'Laser', 'Pied', 'Compresseur',
    ],
  },
  {
    themeId: 'electronique',
    words: [
      'Laptop', 'Tablette', 'Smartphone', 'Ordinateur', 'Moniteur', 'Clavier', 'Souris', 'Casque', 'Hautparleur', 'Microphone',
      'Camera', 'Routeur', 'Modem', 'Imprimante', 'Scanner', 'Television', 'Projecteur', 'Manette', 'Console', 'Chargeur',
      'Powerbank', 'CleUSB', 'Disquedur', 'Drone', 'Webcam', 'Ecran', 'Processeur', 'Adaptateur', 'Batterie', 'Capteur',
      'Bluetooth', 'Wifi', 'Ethernet', 'Microchip', 'Ampli', 'Convertisseur', 'Onduleur', 'Commutateur', 'Emetteur', 'Recepteur',
    ],
  },
  {
    themeId: 'qualites',
    words: [
      'Gentil', 'Intelligent', 'Fort', 'Courageux', 'Honnete', 'Creatif', 'Patient', 'Serviable', 'Amical', 'Attentionne',
      'Calme', 'Cool', 'Drole', 'Serieux', 'Fiable', 'Ambitieux', 'Sociable', 'Precis', 'Flexible', 'Ingenieux',
      'Modeste', 'Franc', 'Determine', 'Optimiste', 'Pessimiste', 'Charismatique', 'Curieux', 'Devoue', 'Attentif', 'Fidele',
      'Doux', 'Strict', 'Sensible', 'Pose', 'Ardent', 'Ordonne', 'Joyeux', 'Pragmatique', 'Logique', 'Empathique',
      'Pratique', 'Habile', 'Resolue', 'Integre', 'Autonome', 'Soigneux', 'Vaillant', 'Energique', 'Sincere', 'Audacieux',
    ],
  },
  {
    themeId: 'couleurs',
    words: [
      'Rouge', 'Jaune', 'Blanc', 'Rose', 'Gris', 'Or', 'Ocre', 'Lilas', 'Ecru', 'Aqua',
      'Jade', 'Saumon', 'Bleu', 'Vert', 'Brun', 'Rouille', 'Ambre', 'Olive', 'Mauve', 'Cyan',
      'Ivoire', 'Beige', 'Bronze', 'Cuivre', 'Violet', 'Noir', 'Azur', 'Taupe', 'Creme', 'Sepia',
      'Corail', 'Indigo', 'Cobalt', 'Argent', 'Orange', 'Marine', 'Moutarde', 'Lavande', 'Turquoise', 'Magenta',
      'Fuchsia', 'Cramoisi', 'Anthracite', 'Bordeaux', 'Marron', 'Menthe', 'Pastel', 'Ecarlate', 'Terracotta', 'Sable',
    ],
  },
  {
    themeId: 'corps',
    words: [
      'Oeil', 'Oreille', 'Bras', 'Jambe', 'Hanche', 'Machoire', 'Orteil', 'Cote', 'Levre', 'Gencive',
      'Tibia', 'Genou', 'Nez', 'Dos', 'Cou', 'Talon', 'Main', 'Pied', 'Ongle', 'Cheveux',
      'Peau', 'Os', 'Menton', 'Sourcil', 'Paume', 'Mollet', 'Poignet', 'Cheville', 'Pouce', 'Coude',
      'Joue', 'Poitrine', 'Colonne', 'Cuisse', 'Crane', 'Coeur', 'Ventre', 'Cerveau', 'Dent', 'Doigt',
      'Tempe', 'Langue', 'Aisselle', 'Rein', 'Muscle', 'Paupiere', 'Epaule', 'Estomac', 'Front', 'Rotule',
    ],
  },
  {
    themeId: 'ecole',
    words: [
      'Stylo', 'Encre', 'Livre', 'Bureau', 'Colle', 'Scotch', 'Examen', 'Test', 'Quiz', 'Tableau',
      'Regle', 'Craie', 'Peinture', 'Globe', 'Atlas', 'Classe', 'Note', 'Score', 'Repas', 'Etude',
      'Crayon', 'Chemise', 'Classeur', 'Agrafe', 'Gomme', 'Marqueur', 'Casier', 'Lecon', 'Recre', 'Journal',
      'Compas', 'Palette', 'Placard', 'Scanner', 'Cahier', 'Sac', 'Ciseaux', 'Manuel', 'Exercice', 'Devoir',
      'Agenda', 'Horaire', 'Bibliotheque', 'Salle', 'Professeur', 'Eleve', 'Science', 'Histoire', 'Musique', 'Dessin',
    ],
  },
  {
    themeId: 'musique',
    words: [
      'Tambour', 'Guitare', 'Piano', 'Violon', 'Trompette', 'Flute', 'Harpe', 'Violoncelle', 'Tuba', 'Trombone',
      'Clarinette', 'Accordeon', 'Ukulele', 'Banjo', 'Saxophone', 'Clavier', 'Xylophone', 'Cloche', 'Cymbale', 'Gong',
      'Basse', 'Tambourin', 'Harmonica', 'Alto', 'Triangle', 'Cornemuse', 'Syntho', 'Microphone', 'Clavecin', 'Rythme',
      'Melodie', 'Accord', 'Harmonie', 'Tempo', 'Hauteur', 'Concert', 'Album', 'Chanson', 'Chanteur', 'Groupe',
      'Solo', 'Duo', 'Orchestre', 'Acoustique', 'Paroles', 'Couplet', 'Pont', 'Riff', 'Groove', 'Remix',
      'Titre', 'Rappel', 'Voix', 'Choeur', 'Repete', 'Festival', 'Scene', 'Studio', 'Chef', 'Volume',
      'Jazz', 'Blues', 'Rock', 'Pop', 'Classique', 'Folk', 'Reggae', 'Gospel', 'Opera', 'Rap',
      'Soul', 'Country', 'Funk', 'Disco', 'Punk', 'Metal', 'Techno', 'Indie', 'Ballade', 'Danse',
      'Swing', 'Valse', 'Grunge', 'Electro', 'Latin', 'Bluegrass', 'Celtique', 'Casque', 'Vinyle', 'Disque',
      'Cassette', 'Platine', 'Stereo', 'Ampli', 'Jukebox', 'Karaoke', 'Podcast', 'Mixeur',
    ],
  },
];

export default fr;
