import type { WordSearchThemeSeed } from '../../engine/seedCorpus';

const nl: WordSearchThemeSeed[] = [
  {
    themeId: 'dieren',
    words: [
      'Hond', 'Kat', 'Paard', 'Koe', 'Schaap', 'Geit', 'Varken', 'Ezel', 'Kameel', 'Lama',
      'Tijger', 'Leeuw', 'Panter', 'Jaguar', 'Luipaard', 'Cheetah', 'Wolf', 'Vos', 'Beer', 'Panda',
      'Wasbeer', 'Bever', 'Otter', 'Hert', 'Ree', 'Bison', 'Buffel', 'Zebra', 'Gnoe', 'Olifant',
      'Neushoorn', 'Nijlpaard', 'Aap', 'Gorilla', 'Chimpansee', 'Maki', 'Slang', 'Hagedis', 'Kikker', 'Pad',
      'Schildpad', 'Arend', 'Havik', 'Uil', 'Duif', 'Kraai', 'Ekster', 'Zwaan', 'Meeuw', 'Reiger',
      'Marter', 'Das', 'Egel', 'Mol', 'Vleermuis', 'Walrus', 'Zeehond', 'Dolfijn', 'Haai', 'Walvis',
      'Kabeljauw', 'Forel', 'Zalm', 'Octopus', 'Krab', 'Garnaal', 'Mier', 'Wesp', 'Bij', 'Libel',
      'Gier', 'Kalkoen', 'Fazant', 'Patrijs', 'Kip', 'Haan', 'Eend', 'Gans', 'Flamingo', 'Pelikaan',
      'Kameleon', 'Leguaan', 'Python', 'Boa', 'Adder', 'Schorpioen', 'Spin', 'Tarantula', 'Termiet', 'Sprinkhaan',
      'Kever', 'Vlinder', 'Mot', 'Zeepaard', 'Rog', 'Tonijn', 'Makreel', 'Sardien', 'Oester', 'Mossel',
      'Paling', 'Inktvis', 'Kreeft', 'Kwal', 'Orca', 'Stier', 'Kokkel', 'Haring', 'Zeester', 'Piranha',
      'Papegaai', 'Pinguin', 'Struisvogel', 'Mus', 'Roodborst', 'Pauw', 'Toekan', 'Ooievaar', 'Kraanvogel', 'Specht',
      'Krokodil', 'Alligator', 'Gekko', 'Cobra', 'Mamba', 'Vuurvlieg', 'Mug', 'Rups', 'Horzel', 'Hommel',
      'Kakkerlak', 'Tor', 'Cicade',
    ],
  },
  {
    themeId: 'eten',
    words: [
      'Appel', 'Peer', 'Banaan', 'Mango', 'Kiwi', 'Druif', 'Kers', 'Pruim', 'Perzik', 'Abrikoos',
      'Aardbei', 'Framboos', 'Braam', 'Bosbes', 'Citroen', 'Limoen', 'Sinaasappel', 'Mandarijn', 'Grapefruit', 'Avocado',
      'Kokosnoot', 'Watermeloen', 'Ananas', 'Papaja', 'Vijg', 'Cranberry', 'Meloen', 'Dadels', 'Guave', 'Wortel',
      'Aardappel', 'Ui', 'Knoflook', 'Erwt', 'Boon', 'Mais', 'Broccoli', 'Spinazie', 'Sla', 'Kool',
      'Tomaat', 'Komkommer', 'Paprika', 'Champignon', 'Selderij', 'Prei', 'Pompoen', 'Courgette', 'Bloemkool', 'Asperge',
      'Biet', 'Boerenkool', 'Radijs', 'Linze', 'Aubergine', 'Venkel', 'Taart', 'Soep', 'Stoof', 'Toast',
      'Salade', 'Pasta', 'Pizza', 'Curry', 'Biefstuk', 'Burger', 'Broodje', 'Pannenkoek', 'Wafel', 'Muffin',
      'Koekje', 'Cake', 'Donut', 'Brownie', 'Noedel', 'Brood', 'Omelet', 'Worst', 'Pudding', 'Gebakje',
      'Granola', 'Bolletje', 'Ham', 'Ei', 'Rijst', 'Rundvlees', 'Varkensvlees', 'Lamsvlees', 'Honing', 'Jam',
      'Kaas', 'Boter', 'Melk', 'Yoghurt', 'Room', 'Thee', 'Koffie', 'Sap', 'Chocolade', 'Gember',
      'Granaatappel', 'Nectarine', 'Artisjok', 'Pastinaak', 'Basilicum', 'Munt', 'Kaneel', 'Vanille', 'Sushi', 'Taco',
      'Risotto', 'Lasagne', 'Croissant', 'Kebab', 'Paella', 'Smoothie', 'Suiker', 'Bloem', 'Siroop', 'Water',
      'Limonade', 'Milkshake', 'Cacao', 'Cider', 'Burrito', 'Ramen', 'Bagel', 'Flensje', 'Falafel',
      'Nachos', 'Dumpling', 'Zout', 'Olie', 'Haver', 'Tofu', 'Drumstick', 'Raap',
    ],
  },
  {
    themeId: 'natuur',
    words: [
      'Roos', 'Tulp', 'Zonnebloem', 'Madeliefje', 'Lavendel', 'Lelie', 'Orchidee', 'Klaproos', 'Iris', 'Viooltje',
      'Anjer', 'Dahlia', 'Narcis', 'Jasmijn', 'Hibiscus', 'Magnolia', 'Boshyacint', 'Sneeuwklokje', 'Sleutelbloem', 'Boterbloem',
      'Heide', 'Klaver', 'Sering', 'Pioenroos', 'Lathyrus', 'Klokjesbloem', 'Eik', 'Berk', 'Esdoorn', 'Wilg',
      'Den', 'Palm', 'Spar', 'Beuk', 'Ceder', 'Olm', 'Es', 'Populier', 'Cipres', 'Lariks',
      'Sequoia', 'Plataan', 'Varen', 'Klimop', 'Cactus', 'Aloevera', 'Paardenbloem', 'Brandnetel', 'Distel', 'Mos',
      'Bamboe', 'Wingerd', 'Regen', 'Sneeuw', 'Storm', 'Donder', 'Bliksem', 'Mist', 'Wolk', 'Wind',
      'Vorst', 'Hagel', 'Ijs', 'Regenboog', 'Sneeuwstorm', 'Tornado', 'Orkaan', 'Motregen', 'Nevel', 'Bries',
      'IJzel', 'Poollicht', 'Zonneschijn', 'Sneeuwvlok', 'Bos', 'Rivier', 'Meer', 'Berg', 'Dal', 'Strand',
      'Woestijn', 'Oceaan', 'Klif', 'Grot', 'Waterval', 'Eiland', 'Weide', 'Gletsjer', 'Vulkaan', 'Jungle',
      'Kloof', 'Moeras', 'Prairie', 'Duin', 'Vijver', 'Beek', 'Rietland', 'Lagune', 'Rif', 'Plateau',
      'Savanne', 'Toendra', 'Veen', 'Fjord', 'Baai', 'Ravijn', 'Bergrug', 'Bergtop', 'Kreek', 'Kiezel',
      'Lente', 'Zomer', 'Herfst', 'Winter', 'Zonsopgang', 'Zonsondergang', 'Eclips', 'Getij', 'Stuifmeel', 'Bodem',
    ],
  },
  {
    themeId: 'sporten',
    words: [
      'Voetbal', 'Handbal', 'Basketbal', 'Volleybal', 'Hockey', 'Tennis', 'Badminton', 'Squash', 'Rugby', 'Honkbal',
      'Softbal', 'Atletiek', 'Sprint', 'Marathon', 'Triatlon', 'Zwemmen', 'Waterpolo', 'Duiken', 'Schermen', 'Judo',
      'Karate', 'Taekwondo', 'Boksen', 'Worstelen', 'Turnen', 'Golf', 'Cricket', 'Skien', 'Snowboarden', 'Schaatsen',
      'Curling', 'Roeien', 'Zeilen', 'Surfen', 'Kitesurfen', 'Windsurfen', 'Kanoen', 'Kajakken', 'Boogschieten', 'Darten',
      'Biljart', 'Snooker', 'Esports', 'Gewichtheffen', 'Paardrijden', 'Wandelen', 'Klimmen', 'Fietsen', 'Joggen', 'Korfbal',
      'Racket', 'Helm', 'Handschoenen', 'Knuppel', 'Golfstok', 'Net', 'Doel', 'Ring', 'Puck', 'Pijl',
      'Boog', 'Mat', 'Baan', 'Fluit', 'Trofee', 'Medaille', 'Scorebord', 'Stopwatch', 'Peddel', 'Touw',
      'Zadel', 'Ski', 'Maillot', 'Noppen',
    ],
  },
  {
    themeId: 'kleding',
    words: [
      'Tshirt', 'Trui', 'Vest', 'Jas', 'Blouse', 'Hemd', 'Polo', 'Topje', 'Broek', 'Jeans',
      'Legging', 'Rok', 'Jurk', 'Short', 'Pyjama', 'Sokken', 'Panty', 'Muts', 'Sjaal', 'Pet',
      'Hoed', 'Sneakers', 'Laarzen', 'Sandalen', 'Hakken', 'Slippers', 'Riem', 'Bikini', 'Badpak', 'Overall',
      'Pak', 'Blazer', 'Hoodie', 'Poncho', 'Kimono', 'Trainingspak', 'Gilet', 'Kousen', 'Regenjas', 'Winterjas',
      'Parka', 'Sweater', 'Handschoenen', 'Wanten', 'Bodywarmer', 'Jumpsuit', 'Tuniek', 'Ochtendjas', 'Cardigan', 'Colbert',
      'Ketting', 'Armband', 'Oorbel', 'Horloge', 'Zonnebril', 'Handtas', 'Portemonnee', 'Paraplu', 'Haarband', 'Strik',
      'Lint', 'Katoen', 'Zijde', 'Wol', 'Linnen', 'Denim', 'Fluweel', 'Leer', 'Polyester', 'Nylon',
      'Fleece', 'Kasjmier', 'Satijn', 'Suede',
    ],
  },
  {
    themeId: 'vervoer',
    words: [
      'Auto', 'Bus', 'Fiets', 'Motor', 'Scooter', 'Step', 'Tractor', 'Heftruck', 'Ambulance', 'Taxi',
      'Limousine', 'Camper', 'Caravan', 'Trein', 'Metro', 'Tram', 'Monorail', 'Boot', 'Zeilboot', 'Motorboot',
      'Duikboot', 'Vliegtuig', 'Helikopter', 'Zeppelin', 'Drone', 'Ruimteschip', 'Quad', 'Sneeuwscooter', 'Bulldozer', 'Truck',
      'Minivan', 'Cabrio', 'Coupe', 'Sedan', 'Segway', 'Hovercraft', 'Jetski', 'Speedboot', 'Skelter', 'Bakfiets',
      'Vrachtwagen', 'Riksja', 'Bromfiets', 'Zweefvliegtuig', 'Veerboot', 'Aak', 'Kano', 'Kajak', 'Vlot', 'Slee',
    ],
  },
  {
    themeId: 'thuis',
    words: [
      'Mes', 'Vork', 'Lepel', 'Spatel', 'Garde', 'Tang', 'Dunschiller', 'Rasp', 'Vergiet', 'Weegschaal',
      'Pan', 'Wok', 'Steelpan', 'Blender', 'Broodrooster', 'Waterkoker', 'Magnetron', 'Oven', 'Fornuis', 'Grill',
      'Pollepel', 'Kom', 'Bord', 'Mok', 'Mixer', 'Bakplaat', 'Rek', 'IJsschep', 'Kop', 'Glas',
      'Kan', 'Fles', 'Theepot', 'Vriezer', 'Keuken', 'Slaapkamer', 'Badkamer', 'Gang', 'Zolder', 'Kelder',
      'Garage', 'Tuin', 'Balkon', 'Studeerkamer', 'Veranda', 'Patio', 'Voorraadkast', 'Kinderkamer', 'Woonkamer', 'Stoel',
      'Bank', 'Tafel', 'Bureau', 'Bed', 'Plank', 'Kledingkast', 'Lade', 'Lamp', 'Spiegel', 'Tapijt',
      'Gordijn', 'Kussen', 'Deken', 'Kast', 'Boekenkast', 'Fauteuil', 'Kruk', 'Ladekast', 'Haard', 'Nachtkastje',
      'Hangmat', 'Vaas', 'Deurmat', 'Koelkast', 'Wasmachine', 'Droger', 'Stofzuiger', 'Vaatwasser', 'Televisie', 'Verwarming',
      'Ventilator', 'Radio', 'Strijkijzer', 'Printer', 'Laptop', 'Telefoon', 'Bezem', 'Dweil', 'Emmer', 'Handdoek',
      'Zeep', 'Kaars', 'Klok', 'Deur', 'Raam', 'Sleutel', 'Douche', 'Bad', 'Mand', 'Hanger',
      'Spons', 'Schop', 'Hark', 'Truweel', 'Kruiwagen', 'Grasmaaier', 'Sproeier', 'Tuinslang', 'Kas', 'Schuur',
      'Hek', 'Poort', 'Heg', 'Gazon', 'Bloempot', 'Compost', 'Snoeischaar', 'Ladder', 'Vogelbad',
    ],
  },
  {
    themeId: 'beroepen',
    words: [
      'Dokter', 'Timmerman', 'Loodgieter', 'Elektricien', 'Bakker', 'Slager', 'Kok', 'Piloot', 'Chauffeur', 'Brandweerman',
      'Advocaat', 'Rechter', 'Schilder', 'Metselaar', 'Architect', 'Ingenieur', 'Programmeur', 'Designer', 'Journalist', 'Schrijver',
      'Dichter', 'Acteur', 'Zanger', 'Muzikant', 'Tuinier', 'Boer', 'Kapper', 'Monteur', 'Trainer', 'Coach',
      'Onderwijzer', 'Professor', 'Verkoper', 'Barista', 'Serveerder', 'Apotheker', 'Laborant', 'Verzorger', 'Therapeut', 'Fotograaf',
      'Kunstenaar', 'Stucadoor', 'Opticien', 'Chirurg', 'Tandarts', 'Analist', 'Boekhouder', 'Regisseur', 'Animator', 'Stylist',
    ],
  },
  {
    themeId: 'familie',
    words: [
      'Vader', 'Moeder', 'Zoon', 'Dochter', 'Broer', 'Zus', 'Opa', 'Oma', 'Oom', 'Tante',
      'Neef', 'Nicht', 'Peetoom', 'Peettante', 'Bruidegom', 'Bruid', 'Echtgenoot', 'Echtgenote', 'Partner', 'Verloofde',
      'Kind', 'Baby', 'Peuter', 'Tiener', 'Volwassene', 'Senior', 'Kleinzoon', 'Kleindochter', 'Stiefvader', 'Stiefmoeder',
      'Stiefbroer', 'Stiefzus', 'Gezin', 'Familie', 'Voorouder', 'Nakomeling', 'Voogd', 'Broertje', 'Zusje', 'Ouder',
      'Neefje', 'Nichtje', 'Tweeling', 'Zuigeling', 'Pasgeborene', 'Wees', 'Weduwe', 'Oudste', 'Verwant', 'Stam',
    ],
  },
  {
    themeId: 'eigenschappen',
    words: [
      'Lief', 'Slim', 'Sterk', 'Dapper', 'Eerlijk', 'Creatief', 'Geduldig', 'Behulpzaam', 'Vriendelijk', 'Zorgzaam',
      'Rustig', 'Stoer', 'Grappig', 'Serieus', 'Betrouwbaar', 'Ambitieus', 'Sociaal', 'Nauwkeurig', 'Flexibel', 'Bescheiden',
      'Zachtaardig', 'Streng', 'Gevoelig', 'Vurig', 'Ordelijk', 'Vrolijk', 'Nuchter', 'Logisch', 'Empathisch', 'Praktisch',
      'Behendig', 'Vastberaden', 'Integer', 'Zelfstandig', 'Zorgvuldig', 'Moedig', 'Energiek', 'Trouw', 'Leergierig', 'Attent',
      'Optimistisch', 'Vastgesteld', 'Charismatisch', 'Vindingrijk', 'Doordacht', 'Ijverig', 'Oprecht', 'Gevat', 'Flink', 'Kordaat',
    ],
  },
  {
    themeId: 'ruimte',
    words: [
      'Ster', 'Planeet', 'Maan', 'Zon', 'Komeet', 'Meteoor', 'Nevel', 'Cluster', 'Supernova', 'Sterrenstelsel',
      'Kwazar', 'Pulsar', 'Vacuum', 'Raket', 'Shuttle', 'Satelliet', 'Telescoop', 'Astronaut', 'Orbit', 'Zwaartekracht',
      'Plasma', 'Materie', 'Krater', 'Kern', 'Mantel', 'Ruimte', 'Heelal', 'Kosmos', 'Duisternis', 'Horizon',
      'Atmosfeer', 'Straling', 'Exoplaneet', 'Baan', 'Lichtjaar', 'Sterrenbeeld', 'Observatorium', 'Kosmonaut', 'Ruimtestation', 'Zwartgat',
      'Melkweg', 'Antimaterie', 'Zonnewind', 'Zonvlam', 'Asteroide', 'Wormgat', 'Nebula', 'Eclips', 'Zonnewende', 'Zenith',
    ],
  },
  {
    themeId: 'kleuren',
    words: [
      'Rood', 'Geel', 'Wit', 'Roze', 'Grijs', 'Goud', 'Oker', 'Lila', 'Ecru', 'Aqua',
      'Jade', 'Zalm', 'Wijn', 'Blauw', 'Groen', 'Bruin', 'Roest', 'Amber', 'Olijf', 'Mauve',
      'Cyaan', 'Ivoor', 'Beige', 'Brons', 'Koper', 'Paars', 'Zwart', 'Azuur', 'Taupe', 'Creme',
      'Sepia', 'Parel', 'Violet', 'Koraal', 'Indigo', 'Kobalt', 'Zilver', 'Oranje', 'Marine', 'Mosterd',
      'Lavendel', 'Turquoise', 'Magenta', 'Fuchsia', 'Karmijn', 'Antraciet', 'Bordeaux', 'Kastanje', 'Mosgroen', 'Mintgroen',
    ],
  },
  {
    themeId: 'lichaamsdelen',
    words: [
      'Oog', 'Oor', 'Arm', 'Rib', 'Lip', 'Rug', 'Nek', 'Bot', 'Kin', 'Dij',
      'Been', 'Heup', 'Kaak', 'Teen', 'Knie', 'Neus', 'Hiel', 'Hand', 'Voet', 'Haar',
      'Huid', 'Palm', 'Kuit', 'Pols', 'Duim', 'Wang', 'Hart', 'Buik', 'Tand', 'Tong',
      'Nier', 'Maag', 'Keel', 'Long', 'Ader', 'Mond', 'Nagel', 'Enkel', 'Borst', 'Brein',
      'Slaap', 'Oksel', 'Spier', 'Lever', 'Navel', 'Hoofd', 'Taille', 'Vinger', 'Ooglid', 'Scheen',
    ],
  },
  {
    themeId: 'school',
    words: [
      'Pen', 'Gum', 'Les', 'Map', 'Inkt', 'Boek', 'Bank', 'Lijm', 'Tape', 'Test',
      'Quiz', 'Bord', 'Verf', 'Klas', 'Niet', 'Kast', 'Bieb', 'Toets', 'Krijt', 'Atlas',
      'Score', 'Lunch', 'Stift', 'Pauze', 'Palet', 'Schaar', 'Bureau', 'Globus', 'Cijfer', 'Studie',
      'Folder', 'Ordner', 'Passer', 'Rugzak', 'Leraar', 'Natuur', 'Potlood', 'Kluisje', 'Dagboek', 'Schrift',
      'Rooster', 'Scanner', 'Liniaal', 'Rapport', 'Leerboek', 'Werkboek', 'Huiswerk', 'Kalender', 'Leerling', 'Klaslokaal',
    ],
  },
  {
    themeId: 'muziek',
    words: [
      'Drum', 'Gitaar', 'Piano', 'Viool', 'Trompet', 'Fluit', 'Harp', 'Cello', 'Tuba', 'Trombone',
      'Klarinet', 'Accordeon', 'Ukulele', 'Banjo', 'Saxofoon', 'Keyboard', 'Recorder', 'Xylofoon', 'Bel', 'Bekkens',
      'Gong', 'Bas', 'Tamboerijn', 'Harmonica', 'Altviool', 'Triangel', 'Doedelzak', 'Synthesizer', 'Microfoon', 'Clavecimbel',
      'Maat', 'Melodie', 'Noot', 'Ritme', 'Refrein', 'Tempo', 'Toonhoogte', 'Akkoord', 'Harmonie', 'Concert',
      'Album', 'Liedje', 'Zanger', 'Band', 'Solo', 'Duet', 'Orkest', 'Akoestisch', 'Tekst', 'Couplet',
      'Brug', 'Riff', 'Groove', 'Remix', 'Track', 'Toegift', 'Stem', 'Koor', 'Repetitie', 'Festival',
      'Podium', 'Studio', 'Componist', 'Dirigent', 'Volume', 'Toon', 'Jazz', 'Blues', 'Rock', 'Pop',
      'Klassiek', 'Folk', 'Reggae', 'Gospel', 'Opera', 'Rap', 'Soul', 'Country', 'Funk', 'Disco',
      'Punk', 'Metal', 'Techno', 'Indie', 'Ballade', 'Dans', 'Swing', 'Wals', 'Grunge', 'Latijn',
      'Luidspreker', 'Hoofdtelefoon', 'Vinyl', 'Plaat', 'Cassette', 'Draaitafel', 'Stereo', 'Versterker', 'Jukebox', 'Karaoke',
      'Podcast', 'Mixer',
    ],
  },
];

export default nl;
